// Code generated by ent, DO NOT EDIT.

package announcementgrouppricechange

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the announcementgrouppricechange type in the database.
	Label = "announcement_group_price_change"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAnnouncementID holds the string denoting the announcement_id field in the database.
	FieldAnnouncementID = "announcement_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldGroupName holds the string denoting the group_name field in the database.
	FieldGroupName = "group_name"
	// FieldOldRate holds the string denoting the old_rate field in the database.
	FieldOldRate = "old_rate"
	// FieldNewRate holds the string denoting the new_rate field in the database.
	FieldNewRate = "new_rate"
	// FieldSequence holds the string denoting the sequence field in the database.
	FieldSequence = "sequence"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeAnnouncement holds the string denoting the announcement edge name in mutations.
	EdgeAnnouncement = "announcement"
	// Table holds the table name of the announcementgrouppricechange in the database.
	Table = "announcement_group_price_changes"
	// AnnouncementTable is the table that holds the announcement relation/edge.
	AnnouncementTable = "announcement_group_price_changes"
	// AnnouncementInverseTable is the table name for the Announcement entity.
	// It exists in this package in order to avoid circular dependency with the "announcement" package.
	AnnouncementInverseTable = "announcements"
	// AnnouncementColumn is the table column denoting the announcement relation/edge.
	AnnouncementColumn = "announcement_id"
)

// Columns holds all SQL columns for announcementgrouppricechange fields.
var Columns = []string{
	FieldID,
	FieldAnnouncementID,
	FieldGroupID,
	FieldGroupName,
	FieldOldRate,
	FieldNewRate,
	FieldSequence,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// GroupNameValidator is a validator for the "group_name" field. It is called by the builders before save.
	GroupNameValidator func(string) error
	// DefaultSequence holds the default value on creation for the "sequence" field.
	DefaultSequence int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the AnnouncementGroupPriceChange queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAnnouncementID orders the results by the announcement_id field.
func ByAnnouncementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnnouncementID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByGroupName orders the results by the group_name field.
func ByGroupName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupName, opts...).ToFunc()
}

// ByOldRate orders the results by the old_rate field.
func ByOldRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOldRate, opts...).ToFunc()
}

// ByNewRate orders the results by the new_rate field.
func ByNewRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNewRate, opts...).ToFunc()
}

// BySequence orders the results by the sequence field.
func BySequence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSequence, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByAnnouncementField orders the results by announcement field.
func ByAnnouncementField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAnnouncementStep(), sql.OrderByField(field, opts...))
	}
}
func newAnnouncementStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AnnouncementInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AnnouncementTable, AnnouncementColumn),
	)
}
