// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcement"
	"github.com/Wei-Shaw/sub2api/ent/announcementgrouppriceread"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AnnouncementGroupPriceReadUpdate is the builder for updating AnnouncementGroupPriceRead entities.
type AnnouncementGroupPriceReadUpdate struct {
	config
	hooks    []Hook
	mutation *AnnouncementGroupPriceReadMutation
}

// Where appends a list predicates to the AnnouncementGroupPriceReadUpdate builder.
func (_u *AnnouncementGroupPriceReadUpdate) Where(ps ...predicate.AnnouncementGroupPriceRead) *AnnouncementGroupPriceReadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAnnouncementID sets the "announcement_id" field.
func (_u *AnnouncementGroupPriceReadUpdate) SetAnnouncementID(v int64) *AnnouncementGroupPriceReadUpdate {
	_u.mutation.SetAnnouncementID(v)
	return _u
}

// SetNillableAnnouncementID sets the "announcement_id" field if the given value is not nil.
func (_u *AnnouncementGroupPriceReadUpdate) SetNillableAnnouncementID(v *int64) *AnnouncementGroupPriceReadUpdate {
	if v != nil {
		_u.SetAnnouncementID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AnnouncementGroupPriceReadUpdate) SetUserID(v int64) *AnnouncementGroupPriceReadUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AnnouncementGroupPriceReadUpdate) SetNillableUserID(v *int64) *AnnouncementGroupPriceReadUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AnnouncementGroupPriceReadUpdate) SetGroupID(v int64) *AnnouncementGroupPriceReadUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AnnouncementGroupPriceReadUpdate) SetNillableGroupID(v *int64) *AnnouncementGroupPriceReadUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *AnnouncementGroupPriceReadUpdate) AddGroupID(v int64) *AnnouncementGroupPriceReadUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *AnnouncementGroupPriceReadUpdate) SetReadAt(v time.Time) *AnnouncementGroupPriceReadUpdate {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *AnnouncementGroupPriceReadUpdate) SetNillableReadAt(v *time.Time) *AnnouncementGroupPriceReadUpdate {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// SetAnnouncement sets the "announcement" edge to the Announcement entity.
func (_u *AnnouncementGroupPriceReadUpdate) SetAnnouncement(v *Announcement) *AnnouncementGroupPriceReadUpdate {
	return _u.SetAnnouncementID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *AnnouncementGroupPriceReadUpdate) SetUser(v *User) *AnnouncementGroupPriceReadUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AnnouncementGroupPriceReadMutation object of the builder.
func (_u *AnnouncementGroupPriceReadUpdate) Mutation() *AnnouncementGroupPriceReadMutation {
	return _u.mutation
}

// ClearAnnouncement clears the "announcement" edge to the Announcement entity.
func (_u *AnnouncementGroupPriceReadUpdate) ClearAnnouncement() *AnnouncementGroupPriceReadUpdate {
	_u.mutation.ClearAnnouncement()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AnnouncementGroupPriceReadUpdate) ClearUser() *AnnouncementGroupPriceReadUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnnouncementGroupPriceReadUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementGroupPriceReadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnnouncementGroupPriceReadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementGroupPriceReadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementGroupPriceReadUpdate) check() error {
	if _u.mutation.AnnouncementCleared() && len(_u.mutation.AnnouncementIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AnnouncementGroupPriceRead.announcement"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AnnouncementGroupPriceRead.user"`)
	}
	return nil
}

func (_u *AnnouncementGroupPriceReadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcementgrouppriceread.Table, announcementgrouppriceread.Columns, sqlgraph.NewFieldSpec(announcementgrouppriceread.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(announcementgrouppriceread.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(announcementgrouppriceread.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(announcementgrouppriceread.FieldReadAt, field.TypeTime, value)
	}
	if _u.mutation.AnnouncementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementgrouppriceread.AnnouncementTable,
			Columns: []string{announcementgrouppriceread.AnnouncementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnnouncementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementgrouppriceread.AnnouncementTable,
			Columns: []string{announcementgrouppriceread.AnnouncementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementgrouppriceread.UserTable,
			Columns: []string{announcementgrouppriceread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementgrouppriceread.UserTable,
			Columns: []string{announcementgrouppriceread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcementgrouppriceread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnnouncementGroupPriceReadUpdateOne is the builder for updating a single AnnouncementGroupPriceRead entity.
type AnnouncementGroupPriceReadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnnouncementGroupPriceReadMutation
}

// SetAnnouncementID sets the "announcement_id" field.
func (_u *AnnouncementGroupPriceReadUpdateOne) SetAnnouncementID(v int64) *AnnouncementGroupPriceReadUpdateOne {
	_u.mutation.SetAnnouncementID(v)
	return _u
}

// SetNillableAnnouncementID sets the "announcement_id" field if the given value is not nil.
func (_u *AnnouncementGroupPriceReadUpdateOne) SetNillableAnnouncementID(v *int64) *AnnouncementGroupPriceReadUpdateOne {
	if v != nil {
		_u.SetAnnouncementID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AnnouncementGroupPriceReadUpdateOne) SetUserID(v int64) *AnnouncementGroupPriceReadUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AnnouncementGroupPriceReadUpdateOne) SetNillableUserID(v *int64) *AnnouncementGroupPriceReadUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AnnouncementGroupPriceReadUpdateOne) SetGroupID(v int64) *AnnouncementGroupPriceReadUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AnnouncementGroupPriceReadUpdateOne) SetNillableGroupID(v *int64) *AnnouncementGroupPriceReadUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *AnnouncementGroupPriceReadUpdateOne) AddGroupID(v int64) *AnnouncementGroupPriceReadUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *AnnouncementGroupPriceReadUpdateOne) SetReadAt(v time.Time) *AnnouncementGroupPriceReadUpdateOne {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *AnnouncementGroupPriceReadUpdateOne) SetNillableReadAt(v *time.Time) *AnnouncementGroupPriceReadUpdateOne {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// SetAnnouncement sets the "announcement" edge to the Announcement entity.
func (_u *AnnouncementGroupPriceReadUpdateOne) SetAnnouncement(v *Announcement) *AnnouncementGroupPriceReadUpdateOne {
	return _u.SetAnnouncementID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *AnnouncementGroupPriceReadUpdateOne) SetUser(v *User) *AnnouncementGroupPriceReadUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AnnouncementGroupPriceReadMutation object of the builder.
func (_u *AnnouncementGroupPriceReadUpdateOne) Mutation() *AnnouncementGroupPriceReadMutation {
	return _u.mutation
}

// ClearAnnouncement clears the "announcement" edge to the Announcement entity.
func (_u *AnnouncementGroupPriceReadUpdateOne) ClearAnnouncement() *AnnouncementGroupPriceReadUpdateOne {
	_u.mutation.ClearAnnouncement()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AnnouncementGroupPriceReadUpdateOne) ClearUser() *AnnouncementGroupPriceReadUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AnnouncementGroupPriceReadUpdate builder.
func (_u *AnnouncementGroupPriceReadUpdateOne) Where(ps ...predicate.AnnouncementGroupPriceRead) *AnnouncementGroupPriceReadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnnouncementGroupPriceReadUpdateOne) Select(field string, fields ...string) *AnnouncementGroupPriceReadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AnnouncementGroupPriceRead entity.
func (_u *AnnouncementGroupPriceReadUpdateOne) Save(ctx context.Context) (*AnnouncementGroupPriceRead, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementGroupPriceReadUpdateOne) SaveX(ctx context.Context) *AnnouncementGroupPriceRead {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnnouncementGroupPriceReadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementGroupPriceReadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementGroupPriceReadUpdateOne) check() error {
	if _u.mutation.AnnouncementCleared() && len(_u.mutation.AnnouncementIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AnnouncementGroupPriceRead.announcement"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AnnouncementGroupPriceRead.user"`)
	}
	return nil
}

func (_u *AnnouncementGroupPriceReadUpdateOne) sqlSave(ctx context.Context) (_node *AnnouncementGroupPriceRead, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcementgrouppriceread.Table, announcementgrouppriceread.Columns, sqlgraph.NewFieldSpec(announcementgrouppriceread.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AnnouncementGroupPriceRead.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, announcementgrouppriceread.FieldID)
		for _, f := range fields {
			if !announcementgrouppriceread.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != announcementgrouppriceread.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(announcementgrouppriceread.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(announcementgrouppriceread.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(announcementgrouppriceread.FieldReadAt, field.TypeTime, value)
	}
	if _u.mutation.AnnouncementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementgrouppriceread.AnnouncementTable,
			Columns: []string{announcementgrouppriceread.AnnouncementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnnouncementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementgrouppriceread.AnnouncementTable,
			Columns: []string{announcementgrouppriceread.AnnouncementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementgrouppriceread.UserTable,
			Columns: []string{announcementgrouppriceread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementgrouppriceread.UserTable,
			Columns: []string{announcementgrouppriceread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AnnouncementGroupPriceRead{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcementgrouppriceread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
