// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcement"
	"github.com/Wei-Shaw/sub2api/ent/announcementgrouppriceread"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AnnouncementGroupPriceReadCreate is the builder for creating a AnnouncementGroupPriceRead entity.
type AnnouncementGroupPriceReadCreate struct {
	config
	mutation *AnnouncementGroupPriceReadMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAnnouncementID sets the "announcement_id" field.
func (_c *AnnouncementGroupPriceReadCreate) SetAnnouncementID(v int64) *AnnouncementGroupPriceReadCreate {
	_c.mutation.SetAnnouncementID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AnnouncementGroupPriceReadCreate) SetUserID(v int64) *AnnouncementGroupPriceReadCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *AnnouncementGroupPriceReadCreate) SetGroupID(v int64) *AnnouncementGroupPriceReadCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetReadAt sets the "read_at" field.
func (_c *AnnouncementGroupPriceReadCreate) SetReadAt(v time.Time) *AnnouncementGroupPriceReadCreate {
	_c.mutation.SetReadAt(v)
	return _c
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_c *AnnouncementGroupPriceReadCreate) SetNillableReadAt(v *time.Time) *AnnouncementGroupPriceReadCreate {
	if v != nil {
		_c.SetReadAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AnnouncementGroupPriceReadCreate) SetCreatedAt(v time.Time) *AnnouncementGroupPriceReadCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AnnouncementGroupPriceReadCreate) SetNillableCreatedAt(v *time.Time) *AnnouncementGroupPriceReadCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAnnouncement sets the "announcement" edge to the Announcement entity.
func (_c *AnnouncementGroupPriceReadCreate) SetAnnouncement(v *Announcement) *AnnouncementGroupPriceReadCreate {
	return _c.SetAnnouncementID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *AnnouncementGroupPriceReadCreate) SetUser(v *User) *AnnouncementGroupPriceReadCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AnnouncementGroupPriceReadMutation object of the builder.
func (_c *AnnouncementGroupPriceReadCreate) Mutation() *AnnouncementGroupPriceReadMutation {
	return _c.mutation
}

// Save creates the AnnouncementGroupPriceRead in the database.
func (_c *AnnouncementGroupPriceReadCreate) Save(ctx context.Context) (*AnnouncementGroupPriceRead, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AnnouncementGroupPriceReadCreate) SaveX(ctx context.Context) *AnnouncementGroupPriceRead {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnnouncementGroupPriceReadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnnouncementGroupPriceReadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AnnouncementGroupPriceReadCreate) defaults() {
	if _, ok := _c.mutation.ReadAt(); !ok {
		v := announcementgrouppriceread.DefaultReadAt()
		_c.mutation.SetReadAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := announcementgrouppriceread.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AnnouncementGroupPriceReadCreate) check() error {
	if _, ok := _c.mutation.AnnouncementID(); !ok {
		return &ValidationError{Name: "announcement_id", err: errors.New(`ent: missing required field "AnnouncementGroupPriceRead.announcement_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AnnouncementGroupPriceRead.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "AnnouncementGroupPriceRead.group_id"`)}
	}
	if _, ok := _c.mutation.ReadAt(); !ok {
		return &ValidationError{Name: "read_at", err: errors.New(`ent: missing required field "AnnouncementGroupPriceRead.read_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AnnouncementGroupPriceRead.created_at"`)}
	}
	if len(_c.mutation.AnnouncementIDs()) == 0 {
		return &ValidationError{Name: "announcement", err: errors.New(`ent: missing required edge "AnnouncementGroupPriceRead.announcement"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AnnouncementGroupPriceRead.user"`)}
	}
	return nil
}

func (_c *AnnouncementGroupPriceReadCreate) sqlSave(ctx context.Context) (*AnnouncementGroupPriceRead, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AnnouncementGroupPriceReadCreate) createSpec() (*AnnouncementGroupPriceRead, *sqlgraph.CreateSpec) {
	var (
		_node = &AnnouncementGroupPriceRead{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(announcementgrouppriceread.Table, sqlgraph.NewFieldSpec(announcementgrouppriceread.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(announcementgrouppriceread.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.ReadAt(); ok {
		_spec.SetField(announcementgrouppriceread.FieldReadAt, field.TypeTime, value)
		_node.ReadAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(announcementgrouppriceread.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.AnnouncementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementgrouppriceread.AnnouncementTable,
			Columns: []string{announcementgrouppriceread.AnnouncementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AnnouncementID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementgrouppriceread.UserTable,
			Columns: []string{announcementgrouppriceread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AnnouncementGroupPriceRead.Create().
//		SetAnnouncementID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AnnouncementGroupPriceReadUpsert) {
//			SetAnnouncementID(v+v).
//		}).
//		Exec(ctx)
func (_c *AnnouncementGroupPriceReadCreate) OnConflict(opts ...sql.ConflictOption) *AnnouncementGroupPriceReadUpsertOne {
	_c.conflict = opts
	return &AnnouncementGroupPriceReadUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AnnouncementGroupPriceRead.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AnnouncementGroupPriceReadCreate) OnConflictColumns(columns ...string) *AnnouncementGroupPriceReadUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AnnouncementGroupPriceReadUpsertOne{
		create: _c,
	}
}

type (
	// AnnouncementGroupPriceReadUpsertOne is the builder for "upsert"-ing
	//  one AnnouncementGroupPriceRead node.
	AnnouncementGroupPriceReadUpsertOne struct {
		create *AnnouncementGroupPriceReadCreate
	}

	// AnnouncementGroupPriceReadUpsert is the "OnConflict" setter.
	AnnouncementGroupPriceReadUpsert struct {
		*sql.UpdateSet
	}
)

// SetAnnouncementID sets the "announcement_id" field.
func (u *AnnouncementGroupPriceReadUpsert) SetAnnouncementID(v int64) *AnnouncementGroupPriceReadUpsert {
	u.Set(announcementgrouppriceread.FieldAnnouncementID, v)
	return u
}

// UpdateAnnouncementID sets the "announcement_id" field to the value that was provided on create.
func (u *AnnouncementGroupPriceReadUpsert) UpdateAnnouncementID() *AnnouncementGroupPriceReadUpsert {
	u.SetExcluded(announcementgrouppriceread.FieldAnnouncementID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AnnouncementGroupPriceReadUpsert) SetUserID(v int64) *AnnouncementGroupPriceReadUpsert {
	u.Set(announcementgrouppriceread.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AnnouncementGroupPriceReadUpsert) UpdateUserID() *AnnouncementGroupPriceReadUpsert {
	u.SetExcluded(announcementgrouppriceread.FieldUserID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *AnnouncementGroupPriceReadUpsert) SetGroupID(v int64) *AnnouncementGroupPriceReadUpsert {
	u.Set(announcementgrouppriceread.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AnnouncementGroupPriceReadUpsert) UpdateGroupID() *AnnouncementGroupPriceReadUpsert {
	u.SetExcluded(announcementgrouppriceread.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *AnnouncementGroupPriceReadUpsert) AddGroupID(v int64) *AnnouncementGroupPriceReadUpsert {
	u.Add(announcementgrouppriceread.FieldGroupID, v)
	return u
}

// SetReadAt sets the "read_at" field.
func (u *AnnouncementGroupPriceReadUpsert) SetReadAt(v time.Time) *AnnouncementGroupPriceReadUpsert {
	u.Set(announcementgrouppriceread.FieldReadAt, v)
	return u
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *AnnouncementGroupPriceReadUpsert) UpdateReadAt() *AnnouncementGroupPriceReadUpsert {
	u.SetExcluded(announcementgrouppriceread.FieldReadAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AnnouncementGroupPriceRead.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AnnouncementGroupPriceReadUpsertOne) UpdateNewValues() *AnnouncementGroupPriceReadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(announcementgrouppriceread.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AnnouncementGroupPriceRead.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AnnouncementGroupPriceReadUpsertOne) Ignore() *AnnouncementGroupPriceReadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AnnouncementGroupPriceReadUpsertOne) DoNothing() *AnnouncementGroupPriceReadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AnnouncementGroupPriceReadCreate.OnConflict
// documentation for more info.
func (u *AnnouncementGroupPriceReadUpsertOne) Update(set func(*AnnouncementGroupPriceReadUpsert)) *AnnouncementGroupPriceReadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AnnouncementGroupPriceReadUpsert{UpdateSet: update})
	}))
	return u
}

// SetAnnouncementID sets the "announcement_id" field.
func (u *AnnouncementGroupPriceReadUpsertOne) SetAnnouncementID(v int64) *AnnouncementGroupPriceReadUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.SetAnnouncementID(v)
	})
}

// UpdateAnnouncementID sets the "announcement_id" field to the value that was provided on create.
func (u *AnnouncementGroupPriceReadUpsertOne) UpdateAnnouncementID() *AnnouncementGroupPriceReadUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.UpdateAnnouncementID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AnnouncementGroupPriceReadUpsertOne) SetUserID(v int64) *AnnouncementGroupPriceReadUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AnnouncementGroupPriceReadUpsertOne) UpdateUserID() *AnnouncementGroupPriceReadUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *AnnouncementGroupPriceReadUpsertOne) SetGroupID(v int64) *AnnouncementGroupPriceReadUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *AnnouncementGroupPriceReadUpsertOne) AddGroupID(v int64) *AnnouncementGroupPriceReadUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AnnouncementGroupPriceReadUpsertOne) UpdateGroupID() *AnnouncementGroupPriceReadUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.UpdateGroupID()
	})
}

// SetReadAt sets the "read_at" field.
func (u *AnnouncementGroupPriceReadUpsertOne) SetReadAt(v time.Time) *AnnouncementGroupPriceReadUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.SetReadAt(v)
	})
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *AnnouncementGroupPriceReadUpsertOne) UpdateReadAt() *AnnouncementGroupPriceReadUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.UpdateReadAt()
	})
}

// Exec executes the query.
func (u *AnnouncementGroupPriceReadUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AnnouncementGroupPriceReadCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AnnouncementGroupPriceReadUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AnnouncementGroupPriceReadUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AnnouncementGroupPriceReadUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AnnouncementGroupPriceReadCreateBulk is the builder for creating many AnnouncementGroupPriceRead entities in bulk.
type AnnouncementGroupPriceReadCreateBulk struct {
	config
	err      error
	builders []*AnnouncementGroupPriceReadCreate
	conflict []sql.ConflictOption
}

// Save creates the AnnouncementGroupPriceRead entities in the database.
func (_c *AnnouncementGroupPriceReadCreateBulk) Save(ctx context.Context) ([]*AnnouncementGroupPriceRead, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AnnouncementGroupPriceRead, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnnouncementGroupPriceReadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AnnouncementGroupPriceReadCreateBulk) SaveX(ctx context.Context) []*AnnouncementGroupPriceRead {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnnouncementGroupPriceReadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnnouncementGroupPriceReadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AnnouncementGroupPriceRead.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AnnouncementGroupPriceReadUpsert) {
//			SetAnnouncementID(v+v).
//		}).
//		Exec(ctx)
func (_c *AnnouncementGroupPriceReadCreateBulk) OnConflict(opts ...sql.ConflictOption) *AnnouncementGroupPriceReadUpsertBulk {
	_c.conflict = opts
	return &AnnouncementGroupPriceReadUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AnnouncementGroupPriceRead.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AnnouncementGroupPriceReadCreateBulk) OnConflictColumns(columns ...string) *AnnouncementGroupPriceReadUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AnnouncementGroupPriceReadUpsertBulk{
		create: _c,
	}
}

// AnnouncementGroupPriceReadUpsertBulk is the builder for "upsert"-ing
// a bulk of AnnouncementGroupPriceRead nodes.
type AnnouncementGroupPriceReadUpsertBulk struct {
	create *AnnouncementGroupPriceReadCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AnnouncementGroupPriceRead.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AnnouncementGroupPriceReadUpsertBulk) UpdateNewValues() *AnnouncementGroupPriceReadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(announcementgrouppriceread.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AnnouncementGroupPriceRead.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AnnouncementGroupPriceReadUpsertBulk) Ignore() *AnnouncementGroupPriceReadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AnnouncementGroupPriceReadUpsertBulk) DoNothing() *AnnouncementGroupPriceReadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AnnouncementGroupPriceReadCreateBulk.OnConflict
// documentation for more info.
func (u *AnnouncementGroupPriceReadUpsertBulk) Update(set func(*AnnouncementGroupPriceReadUpsert)) *AnnouncementGroupPriceReadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AnnouncementGroupPriceReadUpsert{UpdateSet: update})
	}))
	return u
}

// SetAnnouncementID sets the "announcement_id" field.
func (u *AnnouncementGroupPriceReadUpsertBulk) SetAnnouncementID(v int64) *AnnouncementGroupPriceReadUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.SetAnnouncementID(v)
	})
}

// UpdateAnnouncementID sets the "announcement_id" field to the value that was provided on create.
func (u *AnnouncementGroupPriceReadUpsertBulk) UpdateAnnouncementID() *AnnouncementGroupPriceReadUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.UpdateAnnouncementID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AnnouncementGroupPriceReadUpsertBulk) SetUserID(v int64) *AnnouncementGroupPriceReadUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AnnouncementGroupPriceReadUpsertBulk) UpdateUserID() *AnnouncementGroupPriceReadUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *AnnouncementGroupPriceReadUpsertBulk) SetGroupID(v int64) *AnnouncementGroupPriceReadUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *AnnouncementGroupPriceReadUpsertBulk) AddGroupID(v int64) *AnnouncementGroupPriceReadUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AnnouncementGroupPriceReadUpsertBulk) UpdateGroupID() *AnnouncementGroupPriceReadUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.UpdateGroupID()
	})
}

// SetReadAt sets the "read_at" field.
func (u *AnnouncementGroupPriceReadUpsertBulk) SetReadAt(v time.Time) *AnnouncementGroupPriceReadUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.SetReadAt(v)
	})
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *AnnouncementGroupPriceReadUpsertBulk) UpdateReadAt() *AnnouncementGroupPriceReadUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceReadUpsert) {
		s.UpdateReadAt()
	})
}

// Exec executes the query.
func (u *AnnouncementGroupPriceReadUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AnnouncementGroupPriceReadCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AnnouncementGroupPriceReadCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AnnouncementGroupPriceReadUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
