// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcement"
	"github.com/Wei-Shaw/sub2api/ent/announcementgrouppricechange"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AnnouncementGroupPriceChangeQuery is the builder for querying AnnouncementGroupPriceChange entities.
type AnnouncementGroupPriceChangeQuery struct {
	config
	ctx              *QueryContext
	order            []announcementgrouppricechange.OrderOption
	inters           []Interceptor
	predicates       []predicate.AnnouncementGroupPriceChange
	withAnnouncement *AnnouncementQuery
	modifiers        []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AnnouncementGroupPriceChangeQuery builder.
func (_q *AnnouncementGroupPriceChangeQuery) Where(ps ...predicate.AnnouncementGroupPriceChange) *AnnouncementGroupPriceChangeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AnnouncementGroupPriceChangeQuery) Limit(limit int) *AnnouncementGroupPriceChangeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AnnouncementGroupPriceChangeQuery) Offset(offset int) *AnnouncementGroupPriceChangeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AnnouncementGroupPriceChangeQuery) Unique(unique bool) *AnnouncementGroupPriceChangeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AnnouncementGroupPriceChangeQuery) Order(o ...announcementgrouppricechange.OrderOption) *AnnouncementGroupPriceChangeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAnnouncement chains the current query on the "announcement" edge.
func (_q *AnnouncementGroupPriceChangeQuery) QueryAnnouncement() *AnnouncementQuery {
	query := (&AnnouncementClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(announcementgrouppricechange.Table, announcementgrouppricechange.FieldID, selector),
			sqlgraph.To(announcement.Table, announcement.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, announcementgrouppricechange.AnnouncementTable, announcementgrouppricechange.AnnouncementColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AnnouncementGroupPriceChange entity from the query.
// Returns a *NotFoundError when no AnnouncementGroupPriceChange was found.
func (_q *AnnouncementGroupPriceChangeQuery) First(ctx context.Context) (*AnnouncementGroupPriceChange, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{announcementgrouppricechange.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AnnouncementGroupPriceChangeQuery) FirstX(ctx context.Context) *AnnouncementGroupPriceChange {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AnnouncementGroupPriceChange ID from the query.
// Returns a *NotFoundError when no AnnouncementGroupPriceChange ID was found.
func (_q *AnnouncementGroupPriceChangeQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{announcementgrouppricechange.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AnnouncementGroupPriceChangeQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AnnouncementGroupPriceChange entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AnnouncementGroupPriceChange entity is found.
// Returns a *NotFoundError when no AnnouncementGroupPriceChange entities are found.
func (_q *AnnouncementGroupPriceChangeQuery) Only(ctx context.Context) (*AnnouncementGroupPriceChange, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{announcementgrouppricechange.Label}
	default:
		return nil, &NotSingularError{announcementgrouppricechange.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AnnouncementGroupPriceChangeQuery) OnlyX(ctx context.Context) *AnnouncementGroupPriceChange {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AnnouncementGroupPriceChange ID in the query.
// Returns a *NotSingularError when more than one AnnouncementGroupPriceChange ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AnnouncementGroupPriceChangeQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{announcementgrouppricechange.Label}
	default:
		err = &NotSingularError{announcementgrouppricechange.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AnnouncementGroupPriceChangeQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AnnouncementGroupPriceChanges.
func (_q *AnnouncementGroupPriceChangeQuery) All(ctx context.Context) ([]*AnnouncementGroupPriceChange, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AnnouncementGroupPriceChange, *AnnouncementGroupPriceChangeQuery]()
	return withInterceptors[[]*AnnouncementGroupPriceChange](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AnnouncementGroupPriceChangeQuery) AllX(ctx context.Context) []*AnnouncementGroupPriceChange {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AnnouncementGroupPriceChange IDs.
func (_q *AnnouncementGroupPriceChangeQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(announcementgrouppricechange.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AnnouncementGroupPriceChangeQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AnnouncementGroupPriceChangeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AnnouncementGroupPriceChangeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AnnouncementGroupPriceChangeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AnnouncementGroupPriceChangeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AnnouncementGroupPriceChangeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AnnouncementGroupPriceChangeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AnnouncementGroupPriceChangeQuery) Clone() *AnnouncementGroupPriceChangeQuery {
	if _q == nil {
		return nil
	}
	return &AnnouncementGroupPriceChangeQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]announcementgrouppricechange.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.AnnouncementGroupPriceChange{}, _q.predicates...),
		withAnnouncement: _q.withAnnouncement.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAnnouncement tells the query-builder to eager-load the nodes that are connected to
// the "announcement" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AnnouncementGroupPriceChangeQuery) WithAnnouncement(opts ...func(*AnnouncementQuery)) *AnnouncementGroupPriceChangeQuery {
	query := (&AnnouncementClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAnnouncement = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AnnouncementID int64 `json:"announcement_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AnnouncementGroupPriceChange.Query().
//		GroupBy(announcementgrouppricechange.FieldAnnouncementID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AnnouncementGroupPriceChangeQuery) GroupBy(field string, fields ...string) *AnnouncementGroupPriceChangeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AnnouncementGroupPriceChangeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = announcementgrouppricechange.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AnnouncementID int64 `json:"announcement_id,omitempty"`
//	}
//
//	client.AnnouncementGroupPriceChange.Query().
//		Select(announcementgrouppricechange.FieldAnnouncementID).
//		Scan(ctx, &v)
func (_q *AnnouncementGroupPriceChangeQuery) Select(fields ...string) *AnnouncementGroupPriceChangeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AnnouncementGroupPriceChangeSelect{AnnouncementGroupPriceChangeQuery: _q}
	sbuild.label = announcementgrouppricechange.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AnnouncementGroupPriceChangeSelect configured with the given aggregations.
func (_q *AnnouncementGroupPriceChangeQuery) Aggregate(fns ...AggregateFunc) *AnnouncementGroupPriceChangeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AnnouncementGroupPriceChangeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !announcementgrouppricechange.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AnnouncementGroupPriceChangeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AnnouncementGroupPriceChange, error) {
	var (
		nodes       = []*AnnouncementGroupPriceChange{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withAnnouncement != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AnnouncementGroupPriceChange).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AnnouncementGroupPriceChange{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAnnouncement; query != nil {
		if err := _q.loadAnnouncement(ctx, query, nodes, nil,
			func(n *AnnouncementGroupPriceChange, e *Announcement) { n.Edges.Announcement = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AnnouncementGroupPriceChangeQuery) loadAnnouncement(ctx context.Context, query *AnnouncementQuery, nodes []*AnnouncementGroupPriceChange, init func(*AnnouncementGroupPriceChange), assign func(*AnnouncementGroupPriceChange, *Announcement)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*AnnouncementGroupPriceChange)
	for i := range nodes {
		fk := nodes[i].AnnouncementID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(announcement.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "announcement_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *AnnouncementGroupPriceChangeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AnnouncementGroupPriceChangeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(announcementgrouppricechange.Table, announcementgrouppricechange.Columns, sqlgraph.NewFieldSpec(announcementgrouppricechange.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, announcementgrouppricechange.FieldID)
		for i := range fields {
			if fields[i] != announcementgrouppricechange.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withAnnouncement != nil {
			_spec.Node.AddColumnOnce(announcementgrouppricechange.FieldAnnouncementID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AnnouncementGroupPriceChangeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(announcementgrouppricechange.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = announcementgrouppricechange.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *AnnouncementGroupPriceChangeQuery) ForUpdate(opts ...sql.LockOption) *AnnouncementGroupPriceChangeQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *AnnouncementGroupPriceChangeQuery) ForShare(opts ...sql.LockOption) *AnnouncementGroupPriceChangeQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// AnnouncementGroupPriceChangeGroupBy is the group-by builder for AnnouncementGroupPriceChange entities.
type AnnouncementGroupPriceChangeGroupBy struct {
	selector
	build *AnnouncementGroupPriceChangeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AnnouncementGroupPriceChangeGroupBy) Aggregate(fns ...AggregateFunc) *AnnouncementGroupPriceChangeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AnnouncementGroupPriceChangeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AnnouncementGroupPriceChangeQuery, *AnnouncementGroupPriceChangeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AnnouncementGroupPriceChangeGroupBy) sqlScan(ctx context.Context, root *AnnouncementGroupPriceChangeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AnnouncementGroupPriceChangeSelect is the builder for selecting fields of AnnouncementGroupPriceChange entities.
type AnnouncementGroupPriceChangeSelect struct {
	*AnnouncementGroupPriceChangeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AnnouncementGroupPriceChangeSelect) Aggregate(fns ...AggregateFunc) *AnnouncementGroupPriceChangeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AnnouncementGroupPriceChangeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AnnouncementGroupPriceChangeQuery, *AnnouncementGroupPriceChangeSelect](ctx, _s.AnnouncementGroupPriceChangeQuery, _s, _s.inters, v)
}

func (_s *AnnouncementGroupPriceChangeSelect) sqlScan(ctx context.Context, root *AnnouncementGroupPriceChangeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
