// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/announcement"
	"github.com/Wei-Shaw/sub2api/ent/announcementgrouppriceread"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AnnouncementGroupPriceRead is the model entity for the AnnouncementGroupPriceRead schema.
type AnnouncementGroupPriceRead struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AnnouncementID holds the value of the "announcement_id" field.
	AnnouncementID int64 `json:"announcement_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// ReadAt holds the value of the "read_at" field.
	ReadAt time.Time `json:"read_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AnnouncementGroupPriceReadQuery when eager-loading is set.
	Edges        AnnouncementGroupPriceReadEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AnnouncementGroupPriceReadEdges holds the relations/edges for other nodes in the graph.
type AnnouncementGroupPriceReadEdges struct {
	// Announcement holds the value of the announcement edge.
	Announcement *Announcement `json:"announcement,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AnnouncementOrErr returns the Announcement value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AnnouncementGroupPriceReadEdges) AnnouncementOrErr() (*Announcement, error) {
	if e.Announcement != nil {
		return e.Announcement, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: announcement.Label}
	}
	return nil, &NotLoadedError{edge: "announcement"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AnnouncementGroupPriceReadEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AnnouncementGroupPriceRead) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case announcementgrouppriceread.FieldID, announcementgrouppriceread.FieldAnnouncementID, announcementgrouppriceread.FieldUserID, announcementgrouppriceread.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case announcementgrouppriceread.FieldReadAt, announcementgrouppriceread.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AnnouncementGroupPriceRead fields.
func (_m *AnnouncementGroupPriceRead) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case announcementgrouppriceread.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case announcementgrouppriceread.FieldAnnouncementID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field announcement_id", values[i])
			} else if value.Valid {
				_m.AnnouncementID = value.Int64
			}
		case announcementgrouppriceread.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case announcementgrouppriceread.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case announcementgrouppriceread.FieldReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field read_at", values[i])
			} else if value.Valid {
				_m.ReadAt = value.Time
			}
		case announcementgrouppriceread.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AnnouncementGroupPriceRead.
// This includes values selected through modifiers, order, etc.
func (_m *AnnouncementGroupPriceRead) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAnnouncement queries the "announcement" edge of the AnnouncementGroupPriceRead entity.
func (_m *AnnouncementGroupPriceRead) QueryAnnouncement() *AnnouncementQuery {
	return NewAnnouncementGroupPriceReadClient(_m.config).QueryAnnouncement(_m)
}

// QueryUser queries the "user" edge of the AnnouncementGroupPriceRead entity.
func (_m *AnnouncementGroupPriceRead) QueryUser() *UserQuery {
	return NewAnnouncementGroupPriceReadClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this AnnouncementGroupPriceRead.
// Note that you need to call AnnouncementGroupPriceRead.Unwrap() before calling this method if this AnnouncementGroupPriceRead
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AnnouncementGroupPriceRead) Update() *AnnouncementGroupPriceReadUpdateOne {
	return NewAnnouncementGroupPriceReadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AnnouncementGroupPriceRead entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AnnouncementGroupPriceRead) Unwrap() *AnnouncementGroupPriceRead {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AnnouncementGroupPriceRead is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AnnouncementGroupPriceRead) String() string {
	var builder strings.Builder
	builder.WriteString("AnnouncementGroupPriceRead(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("announcement_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AnnouncementID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("read_at=")
	builder.WriteString(_m.ReadAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AnnouncementGroupPriceReads is a parsable slice of AnnouncementGroupPriceRead.
type AnnouncementGroupPriceReads []*AnnouncementGroupPriceRead
