// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcementgrouppriceread"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AnnouncementGroupPriceReadDelete is the builder for deleting a AnnouncementGroupPriceRead entity.
type AnnouncementGroupPriceReadDelete struct {
	config
	hooks    []Hook
	mutation *AnnouncementGroupPriceReadMutation
}

// Where appends a list predicates to the AnnouncementGroupPriceReadDelete builder.
func (_d *AnnouncementGroupPriceReadDelete) Where(ps ...predicate.AnnouncementGroupPriceRead) *AnnouncementGroupPriceReadDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AnnouncementGroupPriceReadDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AnnouncementGroupPriceReadDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AnnouncementGroupPriceReadDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(announcementgrouppriceread.Table, sqlgraph.NewFieldSpec(announcementgrouppriceread.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AnnouncementGroupPriceReadDeleteOne is the builder for deleting a single AnnouncementGroupPriceRead entity.
type AnnouncementGroupPriceReadDeleteOne struct {
	_d *AnnouncementGroupPriceReadDelete
}

// Where appends a list predicates to the AnnouncementGroupPriceReadDelete builder.
func (_d *AnnouncementGroupPriceReadDeleteOne) Where(ps ...predicate.AnnouncementGroupPriceRead) *AnnouncementGroupPriceReadDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AnnouncementGroupPriceReadDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{announcementgrouppriceread.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AnnouncementGroupPriceReadDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
