// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcement"
	"github.com/Wei-Shaw/sub2api/ent/announcementgrouppricechange"
)

// AnnouncementGroupPriceChangeCreate is the builder for creating a AnnouncementGroupPriceChange entity.
type AnnouncementGroupPriceChangeCreate struct {
	config
	mutation *AnnouncementGroupPriceChangeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAnnouncementID sets the "announcement_id" field.
func (_c *AnnouncementGroupPriceChangeCreate) SetAnnouncementID(v int64) *AnnouncementGroupPriceChangeCreate {
	_c.mutation.SetAnnouncementID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *AnnouncementGroupPriceChangeCreate) SetGroupID(v int64) *AnnouncementGroupPriceChangeCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetGroupName sets the "group_name" field.
func (_c *AnnouncementGroupPriceChangeCreate) SetGroupName(v string) *AnnouncementGroupPriceChangeCreate {
	_c.mutation.SetGroupName(v)
	return _c
}

// SetOldRate sets the "old_rate" field.
func (_c *AnnouncementGroupPriceChangeCreate) SetOldRate(v float64) *AnnouncementGroupPriceChangeCreate {
	_c.mutation.SetOldRate(v)
	return _c
}

// SetNewRate sets the "new_rate" field.
func (_c *AnnouncementGroupPriceChangeCreate) SetNewRate(v float64) *AnnouncementGroupPriceChangeCreate {
	_c.mutation.SetNewRate(v)
	return _c
}

// SetSequence sets the "sequence" field.
func (_c *AnnouncementGroupPriceChangeCreate) SetSequence(v int) *AnnouncementGroupPriceChangeCreate {
	_c.mutation.SetSequence(v)
	return _c
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_c *AnnouncementGroupPriceChangeCreate) SetNillableSequence(v *int) *AnnouncementGroupPriceChangeCreate {
	if v != nil {
		_c.SetSequence(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AnnouncementGroupPriceChangeCreate) SetCreatedAt(v time.Time) *AnnouncementGroupPriceChangeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AnnouncementGroupPriceChangeCreate) SetNillableCreatedAt(v *time.Time) *AnnouncementGroupPriceChangeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAnnouncement sets the "announcement" edge to the Announcement entity.
func (_c *AnnouncementGroupPriceChangeCreate) SetAnnouncement(v *Announcement) *AnnouncementGroupPriceChangeCreate {
	return _c.SetAnnouncementID(v.ID)
}

// Mutation returns the AnnouncementGroupPriceChangeMutation object of the builder.
func (_c *AnnouncementGroupPriceChangeCreate) Mutation() *AnnouncementGroupPriceChangeMutation {
	return _c.mutation
}

// Save creates the AnnouncementGroupPriceChange in the database.
func (_c *AnnouncementGroupPriceChangeCreate) Save(ctx context.Context) (*AnnouncementGroupPriceChange, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AnnouncementGroupPriceChangeCreate) SaveX(ctx context.Context) *AnnouncementGroupPriceChange {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnnouncementGroupPriceChangeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnnouncementGroupPriceChangeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AnnouncementGroupPriceChangeCreate) defaults() {
	if _, ok := _c.mutation.Sequence(); !ok {
		v := announcementgrouppricechange.DefaultSequence
		_c.mutation.SetSequence(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := announcementgrouppricechange.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AnnouncementGroupPriceChangeCreate) check() error {
	if _, ok := _c.mutation.AnnouncementID(); !ok {
		return &ValidationError{Name: "announcement_id", err: errors.New(`ent: missing required field "AnnouncementGroupPriceChange.announcement_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "AnnouncementGroupPriceChange.group_id"`)}
	}
	if _, ok := _c.mutation.GroupName(); !ok {
		return &ValidationError{Name: "group_name", err: errors.New(`ent: missing required field "AnnouncementGroupPriceChange.group_name"`)}
	}
	if v, ok := _c.mutation.GroupName(); ok {
		if err := announcementgrouppricechange.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "AnnouncementGroupPriceChange.group_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OldRate(); !ok {
		return &ValidationError{Name: "old_rate", err: errors.New(`ent: missing required field "AnnouncementGroupPriceChange.old_rate"`)}
	}
	if _, ok := _c.mutation.NewRate(); !ok {
		return &ValidationError{Name: "new_rate", err: errors.New(`ent: missing required field "AnnouncementGroupPriceChange.new_rate"`)}
	}
	if _, ok := _c.mutation.Sequence(); !ok {
		return &ValidationError{Name: "sequence", err: errors.New(`ent: missing required field "AnnouncementGroupPriceChange.sequence"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AnnouncementGroupPriceChange.created_at"`)}
	}
	if len(_c.mutation.AnnouncementIDs()) == 0 {
		return &ValidationError{Name: "announcement", err: errors.New(`ent: missing required edge "AnnouncementGroupPriceChange.announcement"`)}
	}
	return nil
}

func (_c *AnnouncementGroupPriceChangeCreate) sqlSave(ctx context.Context) (*AnnouncementGroupPriceChange, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AnnouncementGroupPriceChangeCreate) createSpec() (*AnnouncementGroupPriceChange, *sqlgraph.CreateSpec) {
	var (
		_node = &AnnouncementGroupPriceChange{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(announcementgrouppricechange.Table, sqlgraph.NewFieldSpec(announcementgrouppricechange.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(announcementgrouppricechange.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.GroupName(); ok {
		_spec.SetField(announcementgrouppricechange.FieldGroupName, field.TypeString, value)
		_node.GroupName = value
	}
	if value, ok := _c.mutation.OldRate(); ok {
		_spec.SetField(announcementgrouppricechange.FieldOldRate, field.TypeFloat64, value)
		_node.OldRate = value
	}
	if value, ok := _c.mutation.NewRate(); ok {
		_spec.SetField(announcementgrouppricechange.FieldNewRate, field.TypeFloat64, value)
		_node.NewRate = value
	}
	if value, ok := _c.mutation.Sequence(); ok {
		_spec.SetField(announcementgrouppricechange.FieldSequence, field.TypeInt, value)
		_node.Sequence = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(announcementgrouppricechange.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.AnnouncementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementgrouppricechange.AnnouncementTable,
			Columns: []string{announcementgrouppricechange.AnnouncementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AnnouncementID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AnnouncementGroupPriceChange.Create().
//		SetAnnouncementID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AnnouncementGroupPriceChangeUpsert) {
//			SetAnnouncementID(v+v).
//		}).
//		Exec(ctx)
func (_c *AnnouncementGroupPriceChangeCreate) OnConflict(opts ...sql.ConflictOption) *AnnouncementGroupPriceChangeUpsertOne {
	_c.conflict = opts
	return &AnnouncementGroupPriceChangeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AnnouncementGroupPriceChange.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AnnouncementGroupPriceChangeCreate) OnConflictColumns(columns ...string) *AnnouncementGroupPriceChangeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AnnouncementGroupPriceChangeUpsertOne{
		create: _c,
	}
}

type (
	// AnnouncementGroupPriceChangeUpsertOne is the builder for "upsert"-ing
	//  one AnnouncementGroupPriceChange node.
	AnnouncementGroupPriceChangeUpsertOne struct {
		create *AnnouncementGroupPriceChangeCreate
	}

	// AnnouncementGroupPriceChangeUpsert is the "OnConflict" setter.
	AnnouncementGroupPriceChangeUpsert struct {
		*sql.UpdateSet
	}
)

// SetAnnouncementID sets the "announcement_id" field.
func (u *AnnouncementGroupPriceChangeUpsert) SetAnnouncementID(v int64) *AnnouncementGroupPriceChangeUpsert {
	u.Set(announcementgrouppricechange.FieldAnnouncementID, v)
	return u
}

// UpdateAnnouncementID sets the "announcement_id" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsert) UpdateAnnouncementID() *AnnouncementGroupPriceChangeUpsert {
	u.SetExcluded(announcementgrouppricechange.FieldAnnouncementID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *AnnouncementGroupPriceChangeUpsert) SetGroupID(v int64) *AnnouncementGroupPriceChangeUpsert {
	u.Set(announcementgrouppricechange.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsert) UpdateGroupID() *AnnouncementGroupPriceChangeUpsert {
	u.SetExcluded(announcementgrouppricechange.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *AnnouncementGroupPriceChangeUpsert) AddGroupID(v int64) *AnnouncementGroupPriceChangeUpsert {
	u.Add(announcementgrouppricechange.FieldGroupID, v)
	return u
}

// SetGroupName sets the "group_name" field.
func (u *AnnouncementGroupPriceChangeUpsert) SetGroupName(v string) *AnnouncementGroupPriceChangeUpsert {
	u.Set(announcementgrouppricechange.FieldGroupName, v)
	return u
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsert) UpdateGroupName() *AnnouncementGroupPriceChangeUpsert {
	u.SetExcluded(announcementgrouppricechange.FieldGroupName)
	return u
}

// SetOldRate sets the "old_rate" field.
func (u *AnnouncementGroupPriceChangeUpsert) SetOldRate(v float64) *AnnouncementGroupPriceChangeUpsert {
	u.Set(announcementgrouppricechange.FieldOldRate, v)
	return u
}

// UpdateOldRate sets the "old_rate" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsert) UpdateOldRate() *AnnouncementGroupPriceChangeUpsert {
	u.SetExcluded(announcementgrouppricechange.FieldOldRate)
	return u
}

// AddOldRate adds v to the "old_rate" field.
func (u *AnnouncementGroupPriceChangeUpsert) AddOldRate(v float64) *AnnouncementGroupPriceChangeUpsert {
	u.Add(announcementgrouppricechange.FieldOldRate, v)
	return u
}

// SetNewRate sets the "new_rate" field.
func (u *AnnouncementGroupPriceChangeUpsert) SetNewRate(v float64) *AnnouncementGroupPriceChangeUpsert {
	u.Set(announcementgrouppricechange.FieldNewRate, v)
	return u
}

// UpdateNewRate sets the "new_rate" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsert) UpdateNewRate() *AnnouncementGroupPriceChangeUpsert {
	u.SetExcluded(announcementgrouppricechange.FieldNewRate)
	return u
}

// AddNewRate adds v to the "new_rate" field.
func (u *AnnouncementGroupPriceChangeUpsert) AddNewRate(v float64) *AnnouncementGroupPriceChangeUpsert {
	u.Add(announcementgrouppricechange.FieldNewRate, v)
	return u
}

// SetSequence sets the "sequence" field.
func (u *AnnouncementGroupPriceChangeUpsert) SetSequence(v int) *AnnouncementGroupPriceChangeUpsert {
	u.Set(announcementgrouppricechange.FieldSequence, v)
	return u
}

// UpdateSequence sets the "sequence" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsert) UpdateSequence() *AnnouncementGroupPriceChangeUpsert {
	u.SetExcluded(announcementgrouppricechange.FieldSequence)
	return u
}

// AddSequence adds v to the "sequence" field.
func (u *AnnouncementGroupPriceChangeUpsert) AddSequence(v int) *AnnouncementGroupPriceChangeUpsert {
	u.Add(announcementgrouppricechange.FieldSequence, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AnnouncementGroupPriceChange.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AnnouncementGroupPriceChangeUpsertOne) UpdateNewValues() *AnnouncementGroupPriceChangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(announcementgrouppricechange.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AnnouncementGroupPriceChange.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AnnouncementGroupPriceChangeUpsertOne) Ignore() *AnnouncementGroupPriceChangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AnnouncementGroupPriceChangeUpsertOne) DoNothing() *AnnouncementGroupPriceChangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AnnouncementGroupPriceChangeCreate.OnConflict
// documentation for more info.
func (u *AnnouncementGroupPriceChangeUpsertOne) Update(set func(*AnnouncementGroupPriceChangeUpsert)) *AnnouncementGroupPriceChangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AnnouncementGroupPriceChangeUpsert{UpdateSet: update})
	}))
	return u
}

// SetAnnouncementID sets the "announcement_id" field.
func (u *AnnouncementGroupPriceChangeUpsertOne) SetAnnouncementID(v int64) *AnnouncementGroupPriceChangeUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.SetAnnouncementID(v)
	})
}

// UpdateAnnouncementID sets the "announcement_id" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsertOne) UpdateAnnouncementID() *AnnouncementGroupPriceChangeUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.UpdateAnnouncementID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *AnnouncementGroupPriceChangeUpsertOne) SetGroupID(v int64) *AnnouncementGroupPriceChangeUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *AnnouncementGroupPriceChangeUpsertOne) AddGroupID(v int64) *AnnouncementGroupPriceChangeUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsertOne) UpdateGroupID() *AnnouncementGroupPriceChangeUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.UpdateGroupID()
	})
}

// SetGroupName sets the "group_name" field.
func (u *AnnouncementGroupPriceChangeUpsertOne) SetGroupName(v string) *AnnouncementGroupPriceChangeUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsertOne) UpdateGroupName() *AnnouncementGroupPriceChangeUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.UpdateGroupName()
	})
}

// SetOldRate sets the "old_rate" field.
func (u *AnnouncementGroupPriceChangeUpsertOne) SetOldRate(v float64) *AnnouncementGroupPriceChangeUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.SetOldRate(v)
	})
}

// AddOldRate adds v to the "old_rate" field.
func (u *AnnouncementGroupPriceChangeUpsertOne) AddOldRate(v float64) *AnnouncementGroupPriceChangeUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.AddOldRate(v)
	})
}

// UpdateOldRate sets the "old_rate" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsertOne) UpdateOldRate() *AnnouncementGroupPriceChangeUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.UpdateOldRate()
	})
}

// SetNewRate sets the "new_rate" field.
func (u *AnnouncementGroupPriceChangeUpsertOne) SetNewRate(v float64) *AnnouncementGroupPriceChangeUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.SetNewRate(v)
	})
}

// AddNewRate adds v to the "new_rate" field.
func (u *AnnouncementGroupPriceChangeUpsertOne) AddNewRate(v float64) *AnnouncementGroupPriceChangeUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.AddNewRate(v)
	})
}

// UpdateNewRate sets the "new_rate" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsertOne) UpdateNewRate() *AnnouncementGroupPriceChangeUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.UpdateNewRate()
	})
}

// SetSequence sets the "sequence" field.
func (u *AnnouncementGroupPriceChangeUpsertOne) SetSequence(v int) *AnnouncementGroupPriceChangeUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.SetSequence(v)
	})
}

// AddSequence adds v to the "sequence" field.
func (u *AnnouncementGroupPriceChangeUpsertOne) AddSequence(v int) *AnnouncementGroupPriceChangeUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.AddSequence(v)
	})
}

// UpdateSequence sets the "sequence" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsertOne) UpdateSequence() *AnnouncementGroupPriceChangeUpsertOne {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.UpdateSequence()
	})
}

// Exec executes the query.
func (u *AnnouncementGroupPriceChangeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AnnouncementGroupPriceChangeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AnnouncementGroupPriceChangeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AnnouncementGroupPriceChangeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AnnouncementGroupPriceChangeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AnnouncementGroupPriceChangeCreateBulk is the builder for creating many AnnouncementGroupPriceChange entities in bulk.
type AnnouncementGroupPriceChangeCreateBulk struct {
	config
	err      error
	builders []*AnnouncementGroupPriceChangeCreate
	conflict []sql.ConflictOption
}

// Save creates the AnnouncementGroupPriceChange entities in the database.
func (_c *AnnouncementGroupPriceChangeCreateBulk) Save(ctx context.Context) ([]*AnnouncementGroupPriceChange, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AnnouncementGroupPriceChange, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnnouncementGroupPriceChangeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AnnouncementGroupPriceChangeCreateBulk) SaveX(ctx context.Context) []*AnnouncementGroupPriceChange {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnnouncementGroupPriceChangeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnnouncementGroupPriceChangeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AnnouncementGroupPriceChange.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AnnouncementGroupPriceChangeUpsert) {
//			SetAnnouncementID(v+v).
//		}).
//		Exec(ctx)
func (_c *AnnouncementGroupPriceChangeCreateBulk) OnConflict(opts ...sql.ConflictOption) *AnnouncementGroupPriceChangeUpsertBulk {
	_c.conflict = opts
	return &AnnouncementGroupPriceChangeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AnnouncementGroupPriceChange.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AnnouncementGroupPriceChangeCreateBulk) OnConflictColumns(columns ...string) *AnnouncementGroupPriceChangeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AnnouncementGroupPriceChangeUpsertBulk{
		create: _c,
	}
}

// AnnouncementGroupPriceChangeUpsertBulk is the builder for "upsert"-ing
// a bulk of AnnouncementGroupPriceChange nodes.
type AnnouncementGroupPriceChangeUpsertBulk struct {
	create *AnnouncementGroupPriceChangeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AnnouncementGroupPriceChange.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AnnouncementGroupPriceChangeUpsertBulk) UpdateNewValues() *AnnouncementGroupPriceChangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(announcementgrouppricechange.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AnnouncementGroupPriceChange.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AnnouncementGroupPriceChangeUpsertBulk) Ignore() *AnnouncementGroupPriceChangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AnnouncementGroupPriceChangeUpsertBulk) DoNothing() *AnnouncementGroupPriceChangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AnnouncementGroupPriceChangeCreateBulk.OnConflict
// documentation for more info.
func (u *AnnouncementGroupPriceChangeUpsertBulk) Update(set func(*AnnouncementGroupPriceChangeUpsert)) *AnnouncementGroupPriceChangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AnnouncementGroupPriceChangeUpsert{UpdateSet: update})
	}))
	return u
}

// SetAnnouncementID sets the "announcement_id" field.
func (u *AnnouncementGroupPriceChangeUpsertBulk) SetAnnouncementID(v int64) *AnnouncementGroupPriceChangeUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.SetAnnouncementID(v)
	})
}

// UpdateAnnouncementID sets the "announcement_id" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsertBulk) UpdateAnnouncementID() *AnnouncementGroupPriceChangeUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.UpdateAnnouncementID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *AnnouncementGroupPriceChangeUpsertBulk) SetGroupID(v int64) *AnnouncementGroupPriceChangeUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *AnnouncementGroupPriceChangeUpsertBulk) AddGroupID(v int64) *AnnouncementGroupPriceChangeUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsertBulk) UpdateGroupID() *AnnouncementGroupPriceChangeUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.UpdateGroupID()
	})
}

// SetGroupName sets the "group_name" field.
func (u *AnnouncementGroupPriceChangeUpsertBulk) SetGroupName(v string) *AnnouncementGroupPriceChangeUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsertBulk) UpdateGroupName() *AnnouncementGroupPriceChangeUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.UpdateGroupName()
	})
}

// SetOldRate sets the "old_rate" field.
func (u *AnnouncementGroupPriceChangeUpsertBulk) SetOldRate(v float64) *AnnouncementGroupPriceChangeUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.SetOldRate(v)
	})
}

// AddOldRate adds v to the "old_rate" field.
func (u *AnnouncementGroupPriceChangeUpsertBulk) AddOldRate(v float64) *AnnouncementGroupPriceChangeUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.AddOldRate(v)
	})
}

// UpdateOldRate sets the "old_rate" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsertBulk) UpdateOldRate() *AnnouncementGroupPriceChangeUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.UpdateOldRate()
	})
}

// SetNewRate sets the "new_rate" field.
func (u *AnnouncementGroupPriceChangeUpsertBulk) SetNewRate(v float64) *AnnouncementGroupPriceChangeUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.SetNewRate(v)
	})
}

// AddNewRate adds v to the "new_rate" field.
func (u *AnnouncementGroupPriceChangeUpsertBulk) AddNewRate(v float64) *AnnouncementGroupPriceChangeUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.AddNewRate(v)
	})
}

// UpdateNewRate sets the "new_rate" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsertBulk) UpdateNewRate() *AnnouncementGroupPriceChangeUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.UpdateNewRate()
	})
}

// SetSequence sets the "sequence" field.
func (u *AnnouncementGroupPriceChangeUpsertBulk) SetSequence(v int) *AnnouncementGroupPriceChangeUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.SetSequence(v)
	})
}

// AddSequence adds v to the "sequence" field.
func (u *AnnouncementGroupPriceChangeUpsertBulk) AddSequence(v int) *AnnouncementGroupPriceChangeUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.AddSequence(v)
	})
}

// UpdateSequence sets the "sequence" field to the value that was provided on create.
func (u *AnnouncementGroupPriceChangeUpsertBulk) UpdateSequence() *AnnouncementGroupPriceChangeUpsertBulk {
	return u.Update(func(s *AnnouncementGroupPriceChangeUpsert) {
		s.UpdateSequence()
	})
}

// Exec executes the query.
func (u *AnnouncementGroupPriceChangeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AnnouncementGroupPriceChangeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AnnouncementGroupPriceChangeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AnnouncementGroupPriceChangeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
