// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcement"
	"github.com/Wei-Shaw/sub2api/ent/announcementgrouppricechange"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AnnouncementGroupPriceChangeUpdate is the builder for updating AnnouncementGroupPriceChange entities.
type AnnouncementGroupPriceChangeUpdate struct {
	config
	hooks    []Hook
	mutation *AnnouncementGroupPriceChangeMutation
}

// Where appends a list predicates to the AnnouncementGroupPriceChangeUpdate builder.
func (_u *AnnouncementGroupPriceChangeUpdate) Where(ps ...predicate.AnnouncementGroupPriceChange) *AnnouncementGroupPriceChangeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAnnouncementID sets the "announcement_id" field.
func (_u *AnnouncementGroupPriceChangeUpdate) SetAnnouncementID(v int64) *AnnouncementGroupPriceChangeUpdate {
	_u.mutation.SetAnnouncementID(v)
	return _u
}

// SetNillableAnnouncementID sets the "announcement_id" field if the given value is not nil.
func (_u *AnnouncementGroupPriceChangeUpdate) SetNillableAnnouncementID(v *int64) *AnnouncementGroupPriceChangeUpdate {
	if v != nil {
		_u.SetAnnouncementID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AnnouncementGroupPriceChangeUpdate) SetGroupID(v int64) *AnnouncementGroupPriceChangeUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AnnouncementGroupPriceChangeUpdate) SetNillableGroupID(v *int64) *AnnouncementGroupPriceChangeUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *AnnouncementGroupPriceChangeUpdate) AddGroupID(v int64) *AnnouncementGroupPriceChangeUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *AnnouncementGroupPriceChangeUpdate) SetGroupName(v string) *AnnouncementGroupPriceChangeUpdate {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *AnnouncementGroupPriceChangeUpdate) SetNillableGroupName(v *string) *AnnouncementGroupPriceChangeUpdate {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// SetOldRate sets the "old_rate" field.
func (_u *AnnouncementGroupPriceChangeUpdate) SetOldRate(v float64) *AnnouncementGroupPriceChangeUpdate {
	_u.mutation.ResetOldRate()
	_u.mutation.SetOldRate(v)
	return _u
}

// SetNillableOldRate sets the "old_rate" field if the given value is not nil.
func (_u *AnnouncementGroupPriceChangeUpdate) SetNillableOldRate(v *float64) *AnnouncementGroupPriceChangeUpdate {
	if v != nil {
		_u.SetOldRate(*v)
	}
	return _u
}

// AddOldRate adds value to the "old_rate" field.
func (_u *AnnouncementGroupPriceChangeUpdate) AddOldRate(v float64) *AnnouncementGroupPriceChangeUpdate {
	_u.mutation.AddOldRate(v)
	return _u
}

// SetNewRate sets the "new_rate" field.
func (_u *AnnouncementGroupPriceChangeUpdate) SetNewRate(v float64) *AnnouncementGroupPriceChangeUpdate {
	_u.mutation.ResetNewRate()
	_u.mutation.SetNewRate(v)
	return _u
}

// SetNillableNewRate sets the "new_rate" field if the given value is not nil.
func (_u *AnnouncementGroupPriceChangeUpdate) SetNillableNewRate(v *float64) *AnnouncementGroupPriceChangeUpdate {
	if v != nil {
		_u.SetNewRate(*v)
	}
	return _u
}

// AddNewRate adds value to the "new_rate" field.
func (_u *AnnouncementGroupPriceChangeUpdate) AddNewRate(v float64) *AnnouncementGroupPriceChangeUpdate {
	_u.mutation.AddNewRate(v)
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *AnnouncementGroupPriceChangeUpdate) SetSequence(v int) *AnnouncementGroupPriceChangeUpdate {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *AnnouncementGroupPriceChangeUpdate) SetNillableSequence(v *int) *AnnouncementGroupPriceChangeUpdate {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *AnnouncementGroupPriceChangeUpdate) AddSequence(v int) *AnnouncementGroupPriceChangeUpdate {
	_u.mutation.AddSequence(v)
	return _u
}

// SetAnnouncement sets the "announcement" edge to the Announcement entity.
func (_u *AnnouncementGroupPriceChangeUpdate) SetAnnouncement(v *Announcement) *AnnouncementGroupPriceChangeUpdate {
	return _u.SetAnnouncementID(v.ID)
}

// Mutation returns the AnnouncementGroupPriceChangeMutation object of the builder.
func (_u *AnnouncementGroupPriceChangeUpdate) Mutation() *AnnouncementGroupPriceChangeMutation {
	return _u.mutation
}

// ClearAnnouncement clears the "announcement" edge to the Announcement entity.
func (_u *AnnouncementGroupPriceChangeUpdate) ClearAnnouncement() *AnnouncementGroupPriceChangeUpdate {
	_u.mutation.ClearAnnouncement()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnnouncementGroupPriceChangeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementGroupPriceChangeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnnouncementGroupPriceChangeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementGroupPriceChangeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementGroupPriceChangeUpdate) check() error {
	if v, ok := _u.mutation.GroupName(); ok {
		if err := announcementgrouppricechange.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "AnnouncementGroupPriceChange.group_name": %w`, err)}
		}
	}
	if _u.mutation.AnnouncementCleared() && len(_u.mutation.AnnouncementIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AnnouncementGroupPriceChange.announcement"`)
	}
	return nil
}

func (_u *AnnouncementGroupPriceChangeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcementgrouppricechange.Table, announcementgrouppricechange.Columns, sqlgraph.NewFieldSpec(announcementgrouppricechange.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(announcementgrouppricechange.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(announcementgrouppricechange.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(announcementgrouppricechange.FieldGroupName, field.TypeString, value)
	}
	if value, ok := _u.mutation.OldRate(); ok {
		_spec.SetField(announcementgrouppricechange.FieldOldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOldRate(); ok {
		_spec.AddField(announcementgrouppricechange.FieldOldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.NewRate(); ok {
		_spec.SetField(announcementgrouppricechange.FieldNewRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedNewRate(); ok {
		_spec.AddField(announcementgrouppricechange.FieldNewRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(announcementgrouppricechange.FieldSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(announcementgrouppricechange.FieldSequence, field.TypeInt, value)
	}
	if _u.mutation.AnnouncementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementgrouppricechange.AnnouncementTable,
			Columns: []string{announcementgrouppricechange.AnnouncementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnnouncementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementgrouppricechange.AnnouncementTable,
			Columns: []string{announcementgrouppricechange.AnnouncementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcementgrouppricechange.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnnouncementGroupPriceChangeUpdateOne is the builder for updating a single AnnouncementGroupPriceChange entity.
type AnnouncementGroupPriceChangeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnnouncementGroupPriceChangeMutation
}

// SetAnnouncementID sets the "announcement_id" field.
func (_u *AnnouncementGroupPriceChangeUpdateOne) SetAnnouncementID(v int64) *AnnouncementGroupPriceChangeUpdateOne {
	_u.mutation.SetAnnouncementID(v)
	return _u
}

// SetNillableAnnouncementID sets the "announcement_id" field if the given value is not nil.
func (_u *AnnouncementGroupPriceChangeUpdateOne) SetNillableAnnouncementID(v *int64) *AnnouncementGroupPriceChangeUpdateOne {
	if v != nil {
		_u.SetAnnouncementID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AnnouncementGroupPriceChangeUpdateOne) SetGroupID(v int64) *AnnouncementGroupPriceChangeUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AnnouncementGroupPriceChangeUpdateOne) SetNillableGroupID(v *int64) *AnnouncementGroupPriceChangeUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *AnnouncementGroupPriceChangeUpdateOne) AddGroupID(v int64) *AnnouncementGroupPriceChangeUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *AnnouncementGroupPriceChangeUpdateOne) SetGroupName(v string) *AnnouncementGroupPriceChangeUpdateOne {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *AnnouncementGroupPriceChangeUpdateOne) SetNillableGroupName(v *string) *AnnouncementGroupPriceChangeUpdateOne {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// SetOldRate sets the "old_rate" field.
func (_u *AnnouncementGroupPriceChangeUpdateOne) SetOldRate(v float64) *AnnouncementGroupPriceChangeUpdateOne {
	_u.mutation.ResetOldRate()
	_u.mutation.SetOldRate(v)
	return _u
}

// SetNillableOldRate sets the "old_rate" field if the given value is not nil.
func (_u *AnnouncementGroupPriceChangeUpdateOne) SetNillableOldRate(v *float64) *AnnouncementGroupPriceChangeUpdateOne {
	if v != nil {
		_u.SetOldRate(*v)
	}
	return _u
}

// AddOldRate adds value to the "old_rate" field.
func (_u *AnnouncementGroupPriceChangeUpdateOne) AddOldRate(v float64) *AnnouncementGroupPriceChangeUpdateOne {
	_u.mutation.AddOldRate(v)
	return _u
}

// SetNewRate sets the "new_rate" field.
func (_u *AnnouncementGroupPriceChangeUpdateOne) SetNewRate(v float64) *AnnouncementGroupPriceChangeUpdateOne {
	_u.mutation.ResetNewRate()
	_u.mutation.SetNewRate(v)
	return _u
}

// SetNillableNewRate sets the "new_rate" field if the given value is not nil.
func (_u *AnnouncementGroupPriceChangeUpdateOne) SetNillableNewRate(v *float64) *AnnouncementGroupPriceChangeUpdateOne {
	if v != nil {
		_u.SetNewRate(*v)
	}
	return _u
}

// AddNewRate adds value to the "new_rate" field.
func (_u *AnnouncementGroupPriceChangeUpdateOne) AddNewRate(v float64) *AnnouncementGroupPriceChangeUpdateOne {
	_u.mutation.AddNewRate(v)
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *AnnouncementGroupPriceChangeUpdateOne) SetSequence(v int) *AnnouncementGroupPriceChangeUpdateOne {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *AnnouncementGroupPriceChangeUpdateOne) SetNillableSequence(v *int) *AnnouncementGroupPriceChangeUpdateOne {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *AnnouncementGroupPriceChangeUpdateOne) AddSequence(v int) *AnnouncementGroupPriceChangeUpdateOne {
	_u.mutation.AddSequence(v)
	return _u
}

// SetAnnouncement sets the "announcement" edge to the Announcement entity.
func (_u *AnnouncementGroupPriceChangeUpdateOne) SetAnnouncement(v *Announcement) *AnnouncementGroupPriceChangeUpdateOne {
	return _u.SetAnnouncementID(v.ID)
}

// Mutation returns the AnnouncementGroupPriceChangeMutation object of the builder.
func (_u *AnnouncementGroupPriceChangeUpdateOne) Mutation() *AnnouncementGroupPriceChangeMutation {
	return _u.mutation
}

// ClearAnnouncement clears the "announcement" edge to the Announcement entity.
func (_u *AnnouncementGroupPriceChangeUpdateOne) ClearAnnouncement() *AnnouncementGroupPriceChangeUpdateOne {
	_u.mutation.ClearAnnouncement()
	return _u
}

// Where appends a list predicates to the AnnouncementGroupPriceChangeUpdate builder.
func (_u *AnnouncementGroupPriceChangeUpdateOne) Where(ps ...predicate.AnnouncementGroupPriceChange) *AnnouncementGroupPriceChangeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnnouncementGroupPriceChangeUpdateOne) Select(field string, fields ...string) *AnnouncementGroupPriceChangeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AnnouncementGroupPriceChange entity.
func (_u *AnnouncementGroupPriceChangeUpdateOne) Save(ctx context.Context) (*AnnouncementGroupPriceChange, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementGroupPriceChangeUpdateOne) SaveX(ctx context.Context) *AnnouncementGroupPriceChange {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnnouncementGroupPriceChangeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementGroupPriceChangeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementGroupPriceChangeUpdateOne) check() error {
	if v, ok := _u.mutation.GroupName(); ok {
		if err := announcementgrouppricechange.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "AnnouncementGroupPriceChange.group_name": %w`, err)}
		}
	}
	if _u.mutation.AnnouncementCleared() && len(_u.mutation.AnnouncementIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AnnouncementGroupPriceChange.announcement"`)
	}
	return nil
}

func (_u *AnnouncementGroupPriceChangeUpdateOne) sqlSave(ctx context.Context) (_node *AnnouncementGroupPriceChange, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcementgrouppricechange.Table, announcementgrouppricechange.Columns, sqlgraph.NewFieldSpec(announcementgrouppricechange.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AnnouncementGroupPriceChange.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, announcementgrouppricechange.FieldID)
		for _, f := range fields {
			if !announcementgrouppricechange.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != announcementgrouppricechange.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(announcementgrouppricechange.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(announcementgrouppricechange.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(announcementgrouppricechange.FieldGroupName, field.TypeString, value)
	}
	if value, ok := _u.mutation.OldRate(); ok {
		_spec.SetField(announcementgrouppricechange.FieldOldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOldRate(); ok {
		_spec.AddField(announcementgrouppricechange.FieldOldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.NewRate(); ok {
		_spec.SetField(announcementgrouppricechange.FieldNewRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedNewRate(); ok {
		_spec.AddField(announcementgrouppricechange.FieldNewRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(announcementgrouppricechange.FieldSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(announcementgrouppricechange.FieldSequence, field.TypeInt, value)
	}
	if _u.mutation.AnnouncementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementgrouppricechange.AnnouncementTable,
			Columns: []string{announcementgrouppricechange.AnnouncementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnnouncementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementgrouppricechange.AnnouncementTable,
			Columns: []string{announcementgrouppricechange.AnnouncementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AnnouncementGroupPriceChange{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcementgrouppricechange.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
