// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grokvideojob"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GrokVideoJobDelete is the builder for deleting a GrokVideoJob entity.
type GrokVideoJobDelete struct {
	config
	hooks    []Hook
	mutation *GrokVideoJobMutation
}

// Where appends a list predicates to the GrokVideoJobDelete builder.
func (_d *GrokVideoJobDelete) Where(ps ...predicate.GrokVideoJob) *GrokVideoJobDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GrokVideoJobDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GrokVideoJobDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GrokVideoJobDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(grokvideojob.Table, sqlgraph.NewFieldSpec(grokvideojob.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GrokVideoJobDeleteOne is the builder for deleting a single GrokVideoJob entity.
type GrokVideoJobDeleteOne struct {
	_d *GrokVideoJobDelete
}

// Where appends a list predicates to the GrokVideoJobDelete builder.
func (_d *GrokVideoJobDeleteOne) Where(ps ...predicate.GrokVideoJob) *GrokVideoJobDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GrokVideoJobDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{grokvideojob.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GrokVideoJobDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
