// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grokvideojob"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GrokVideoJobUpdate is the builder for updating GrokVideoJob entities.
type GrokVideoJobUpdate struct {
	config
	hooks    []Hook
	mutation *GrokVideoJobMutation
}

// Where appends a list predicates to the GrokVideoJobUpdate builder.
func (_u *GrokVideoJobUpdate) Where(ps ...predicate.GrokVideoJob) *GrokVideoJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GrokVideoJobUpdate) SetUserID(v int64) *GrokVideoJobUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillableUserID(v *int64) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *GrokVideoJobUpdate) AddUserID(v int64) *GrokVideoJobUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *GrokVideoJobUpdate) SetAPIKeyID(v int64) *GrokVideoJobUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillableAPIKeyID(v *int64) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *GrokVideoJobUpdate) AddAPIKeyID(v int64) *GrokVideoJobUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *GrokVideoJobUpdate) ClearAPIKeyID() *GrokVideoJobUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GrokVideoJobUpdate) SetGroupID(v int64) *GrokVideoJobUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillableGroupID(v *int64) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *GrokVideoJobUpdate) AddGroupID(v int64) *GrokVideoJobUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *GrokVideoJobUpdate) ClearGroupID() *GrokVideoJobUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *GrokVideoJobUpdate) SetAccountID(v int64) *GrokVideoJobUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillableAccountID(v *int64) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *GrokVideoJobUpdate) AddAccountID(v int64) *GrokVideoJobUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *GrokVideoJobUpdate) ClearAccountID() *GrokVideoJobUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetModel sets the "model" field.
func (_u *GrokVideoJobUpdate) SetModel(v string) *GrokVideoJobUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillableModel(v *string) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetPromptPreview sets the "prompt_preview" field.
func (_u *GrokVideoJobUpdate) SetPromptPreview(v string) *GrokVideoJobUpdate {
	_u.mutation.SetPromptPreview(v)
	return _u
}

// SetNillablePromptPreview sets the "prompt_preview" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillablePromptPreview(v *string) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetPromptPreview(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GrokVideoJobUpdate) SetStatus(v string) *GrokVideoJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillableStatus(v *string) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProgressPercent sets the "progress_percent" field.
func (_u *GrokVideoJobUpdate) SetProgressPercent(v int) *GrokVideoJobUpdate {
	_u.mutation.ResetProgressPercent()
	_u.mutation.SetProgressPercent(v)
	return _u
}

// SetNillableProgressPercent sets the "progress_percent" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillableProgressPercent(v *int) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetProgressPercent(*v)
	}
	return _u
}

// AddProgressPercent adds value to the "progress_percent" field.
func (_u *GrokVideoJobUpdate) AddProgressPercent(v int) *GrokVideoJobUpdate {
	_u.mutation.AddProgressPercent(v)
	return _u
}

// SetProgressText sets the "progress_text" field.
func (_u *GrokVideoJobUpdate) SetProgressText(v string) *GrokVideoJobUpdate {
	_u.mutation.SetProgressText(v)
	return _u
}

// SetNillableProgressText sets the "progress_text" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillableProgressText(v *string) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetProgressText(*v)
	}
	return _u
}

// SetResultURL sets the "result_url" field.
func (_u *GrokVideoJobUpdate) SetResultURL(v string) *GrokVideoJobUpdate {
	_u.mutation.SetResultURL(v)
	return _u
}

// SetNillableResultURL sets the "result_url" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillableResultURL(v *string) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetResultURL(*v)
	}
	return _u
}

// ClearResultURL clears the value of the "result_url" field.
func (_u *GrokVideoJobUpdate) ClearResultURL() *GrokVideoJobUpdate {
	_u.mutation.ClearResultURL()
	return _u
}

// SetResultUrls sets the "result_urls" field.
func (_u *GrokVideoJobUpdate) SetResultUrls(v string) *GrokVideoJobUpdate {
	_u.mutation.SetResultUrls(v)
	return _u
}

// SetNillableResultUrls sets the "result_urls" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillableResultUrls(v *string) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetResultUrls(*v)
	}
	return _u
}

// ClearResultUrls clears the value of the "result_urls" field.
func (_u *GrokVideoJobUpdate) ClearResultUrls() *GrokVideoJobUpdate {
	_u.mutation.ClearResultUrls()
	return _u
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_u *GrokVideoJobUpdate) SetCoverImageURL(v string) *GrokVideoJobUpdate {
	_u.mutation.SetCoverImageURL(v)
	return _u
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillableCoverImageURL(v *string) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetCoverImageURL(*v)
	}
	return _u
}

// ClearCoverImageURL clears the value of the "cover_image_url" field.
func (_u *GrokVideoJobUpdate) ClearCoverImageURL() *GrokVideoJobUpdate {
	_u.mutation.ClearCoverImageURL()
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *GrokVideoJobUpdate) SetLastErrorCode(v string) *GrokVideoJobUpdate {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillableLastErrorCode(v *string) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (_u *GrokVideoJobUpdate) ClearLastErrorCode() *GrokVideoJobUpdate {
	_u.mutation.ClearLastErrorCode()
	return _u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_u *GrokVideoJobUpdate) SetLastErrorMessage(v string) *GrokVideoJobUpdate {
	_u.mutation.SetLastErrorMessage(v)
	return _u
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillableLastErrorMessage(v *string) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetLastErrorMessage(*v)
	}
	return _u
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (_u *GrokVideoJobUpdate) ClearLastErrorMessage() *GrokVideoJobUpdate {
	_u.mutation.ClearLastErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GrokVideoJobUpdate) SetUpdatedAt(v time.Time) *GrokVideoJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *GrokVideoJobUpdate) SetSubmittedAt(v time.Time) *GrokVideoJobUpdate {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillableSubmittedAt(v *time.Time) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// SetLastPolledAt sets the "last_polled_at" field.
func (_u *GrokVideoJobUpdate) SetLastPolledAt(v time.Time) *GrokVideoJobUpdate {
	_u.mutation.SetLastPolledAt(v)
	return _u
}

// SetNillableLastPolledAt sets the "last_polled_at" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillableLastPolledAt(v *time.Time) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetLastPolledAt(*v)
	}
	return _u
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (_u *GrokVideoJobUpdate) ClearLastPolledAt() *GrokVideoJobUpdate {
	_u.mutation.ClearLastPolledAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *GrokVideoJobUpdate) SetFinishedAt(v time.Time) *GrokVideoJobUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *GrokVideoJobUpdate) SetNillableFinishedAt(v *time.Time) *GrokVideoJobUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *GrokVideoJobUpdate) ClearFinishedAt() *GrokVideoJobUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the GrokVideoJobMutation object of the builder.
func (_u *GrokVideoJobUpdate) Mutation() *GrokVideoJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GrokVideoJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GrokVideoJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GrokVideoJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GrokVideoJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GrokVideoJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := grokvideojob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GrokVideoJobUpdate) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := grokvideojob.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "GrokVideoJob.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromptPreview(); ok {
		if err := grokvideojob.PromptPreviewValidator(v); err != nil {
			return &ValidationError{Name: "prompt_preview", err: fmt.Errorf(`ent: validator failed for field "GrokVideoJob.prompt_preview": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := grokvideojob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GrokVideoJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProgressText(); ok {
		if err := grokvideojob.ProgressTextValidator(v); err != nil {
			return &ValidationError{Name: "progress_text", err: fmt.Errorf(`ent: validator failed for field "GrokVideoJob.progress_text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorCode(); ok {
		if err := grokvideojob.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "GrokVideoJob.last_error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *GrokVideoJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grokvideojob.Table, grokvideojob.Columns, sqlgraph.NewFieldSpec(grokvideojob.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(grokvideojob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(grokvideojob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(grokvideojob.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(grokvideojob.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(grokvideojob.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(grokvideojob.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(grokvideojob.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(grokvideojob.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(grokvideojob.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(grokvideojob.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(grokvideojob.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(grokvideojob.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromptPreview(); ok {
		_spec.SetField(grokvideojob.FieldPromptPreview, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(grokvideojob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProgressPercent(); ok {
		_spec.SetField(grokvideojob.FieldProgressPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgressPercent(); ok {
		_spec.AddField(grokvideojob.FieldProgressPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProgressText(); ok {
		_spec.SetField(grokvideojob.FieldProgressText, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResultURL(); ok {
		_spec.SetField(grokvideojob.FieldResultURL, field.TypeString, value)
	}
	if _u.mutation.ResultURLCleared() {
		_spec.ClearField(grokvideojob.FieldResultURL, field.TypeString)
	}
	if value, ok := _u.mutation.ResultUrls(); ok {
		_spec.SetField(grokvideojob.FieldResultUrls, field.TypeString, value)
	}
	if _u.mutation.ResultUrlsCleared() {
		_spec.ClearField(grokvideojob.FieldResultUrls, field.TypeString)
	}
	if value, ok := _u.mutation.CoverImageURL(); ok {
		_spec.SetField(grokvideojob.FieldCoverImageURL, field.TypeString, value)
	}
	if _u.mutation.CoverImageURLCleared() {
		_spec.ClearField(grokvideojob.FieldCoverImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(grokvideojob.FieldLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastErrorCodeCleared() {
		_spec.ClearField(grokvideojob.FieldLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorMessage(); ok {
		_spec.SetField(grokvideojob.FieldLastErrorMessage, field.TypeString, value)
	}
	if _u.mutation.LastErrorMessageCleared() {
		_spec.ClearField(grokvideojob.FieldLastErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(grokvideojob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(grokvideojob.FieldSubmittedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastPolledAt(); ok {
		_spec.SetField(grokvideojob.FieldLastPolledAt, field.TypeTime, value)
	}
	if _u.mutation.LastPolledAtCleared() {
		_spec.ClearField(grokvideojob.FieldLastPolledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(grokvideojob.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(grokvideojob.FieldFinishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grokvideojob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GrokVideoJobUpdateOne is the builder for updating a single GrokVideoJob entity.
type GrokVideoJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GrokVideoJobMutation
}

// SetUserID sets the "user_id" field.
func (_u *GrokVideoJobUpdateOne) SetUserID(v int64) *GrokVideoJobUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillableUserID(v *int64) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *GrokVideoJobUpdateOne) AddUserID(v int64) *GrokVideoJobUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *GrokVideoJobUpdateOne) SetAPIKeyID(v int64) *GrokVideoJobUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillableAPIKeyID(v *int64) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *GrokVideoJobUpdateOne) AddAPIKeyID(v int64) *GrokVideoJobUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *GrokVideoJobUpdateOne) ClearAPIKeyID() *GrokVideoJobUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GrokVideoJobUpdateOne) SetGroupID(v int64) *GrokVideoJobUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillableGroupID(v *int64) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *GrokVideoJobUpdateOne) AddGroupID(v int64) *GrokVideoJobUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *GrokVideoJobUpdateOne) ClearGroupID() *GrokVideoJobUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *GrokVideoJobUpdateOne) SetAccountID(v int64) *GrokVideoJobUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillableAccountID(v *int64) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *GrokVideoJobUpdateOne) AddAccountID(v int64) *GrokVideoJobUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *GrokVideoJobUpdateOne) ClearAccountID() *GrokVideoJobUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetModel sets the "model" field.
func (_u *GrokVideoJobUpdateOne) SetModel(v string) *GrokVideoJobUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillableModel(v *string) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetPromptPreview sets the "prompt_preview" field.
func (_u *GrokVideoJobUpdateOne) SetPromptPreview(v string) *GrokVideoJobUpdateOne {
	_u.mutation.SetPromptPreview(v)
	return _u
}

// SetNillablePromptPreview sets the "prompt_preview" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillablePromptPreview(v *string) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetPromptPreview(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GrokVideoJobUpdateOne) SetStatus(v string) *GrokVideoJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillableStatus(v *string) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProgressPercent sets the "progress_percent" field.
func (_u *GrokVideoJobUpdateOne) SetProgressPercent(v int) *GrokVideoJobUpdateOne {
	_u.mutation.ResetProgressPercent()
	_u.mutation.SetProgressPercent(v)
	return _u
}

// SetNillableProgressPercent sets the "progress_percent" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillableProgressPercent(v *int) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetProgressPercent(*v)
	}
	return _u
}

// AddProgressPercent adds value to the "progress_percent" field.
func (_u *GrokVideoJobUpdateOne) AddProgressPercent(v int) *GrokVideoJobUpdateOne {
	_u.mutation.AddProgressPercent(v)
	return _u
}

// SetProgressText sets the "progress_text" field.
func (_u *GrokVideoJobUpdateOne) SetProgressText(v string) *GrokVideoJobUpdateOne {
	_u.mutation.SetProgressText(v)
	return _u
}

// SetNillableProgressText sets the "progress_text" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillableProgressText(v *string) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetProgressText(*v)
	}
	return _u
}

// SetResultURL sets the "result_url" field.
func (_u *GrokVideoJobUpdateOne) SetResultURL(v string) *GrokVideoJobUpdateOne {
	_u.mutation.SetResultURL(v)
	return _u
}

// SetNillableResultURL sets the "result_url" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillableResultURL(v *string) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetResultURL(*v)
	}
	return _u
}

// ClearResultURL clears the value of the "result_url" field.
func (_u *GrokVideoJobUpdateOne) ClearResultURL() *GrokVideoJobUpdateOne {
	_u.mutation.ClearResultURL()
	return _u
}

// SetResultUrls sets the "result_urls" field.
func (_u *GrokVideoJobUpdateOne) SetResultUrls(v string) *GrokVideoJobUpdateOne {
	_u.mutation.SetResultUrls(v)
	return _u
}

// SetNillableResultUrls sets the "result_urls" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillableResultUrls(v *string) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetResultUrls(*v)
	}
	return _u
}

// ClearResultUrls clears the value of the "result_urls" field.
func (_u *GrokVideoJobUpdateOne) ClearResultUrls() *GrokVideoJobUpdateOne {
	_u.mutation.ClearResultUrls()
	return _u
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_u *GrokVideoJobUpdateOne) SetCoverImageURL(v string) *GrokVideoJobUpdateOne {
	_u.mutation.SetCoverImageURL(v)
	return _u
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillableCoverImageURL(v *string) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetCoverImageURL(*v)
	}
	return _u
}

// ClearCoverImageURL clears the value of the "cover_image_url" field.
func (_u *GrokVideoJobUpdateOne) ClearCoverImageURL() *GrokVideoJobUpdateOne {
	_u.mutation.ClearCoverImageURL()
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *GrokVideoJobUpdateOne) SetLastErrorCode(v string) *GrokVideoJobUpdateOne {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillableLastErrorCode(v *string) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (_u *GrokVideoJobUpdateOne) ClearLastErrorCode() *GrokVideoJobUpdateOne {
	_u.mutation.ClearLastErrorCode()
	return _u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_u *GrokVideoJobUpdateOne) SetLastErrorMessage(v string) *GrokVideoJobUpdateOne {
	_u.mutation.SetLastErrorMessage(v)
	return _u
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillableLastErrorMessage(v *string) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetLastErrorMessage(*v)
	}
	return _u
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (_u *GrokVideoJobUpdateOne) ClearLastErrorMessage() *GrokVideoJobUpdateOne {
	_u.mutation.ClearLastErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GrokVideoJobUpdateOne) SetUpdatedAt(v time.Time) *GrokVideoJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *GrokVideoJobUpdateOne) SetSubmittedAt(v time.Time) *GrokVideoJobUpdateOne {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillableSubmittedAt(v *time.Time) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// SetLastPolledAt sets the "last_polled_at" field.
func (_u *GrokVideoJobUpdateOne) SetLastPolledAt(v time.Time) *GrokVideoJobUpdateOne {
	_u.mutation.SetLastPolledAt(v)
	return _u
}

// SetNillableLastPolledAt sets the "last_polled_at" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillableLastPolledAt(v *time.Time) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetLastPolledAt(*v)
	}
	return _u
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (_u *GrokVideoJobUpdateOne) ClearLastPolledAt() *GrokVideoJobUpdateOne {
	_u.mutation.ClearLastPolledAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *GrokVideoJobUpdateOne) SetFinishedAt(v time.Time) *GrokVideoJobUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *GrokVideoJobUpdateOne) SetNillableFinishedAt(v *time.Time) *GrokVideoJobUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *GrokVideoJobUpdateOne) ClearFinishedAt() *GrokVideoJobUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the GrokVideoJobMutation object of the builder.
func (_u *GrokVideoJobUpdateOne) Mutation() *GrokVideoJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the GrokVideoJobUpdate builder.
func (_u *GrokVideoJobUpdateOne) Where(ps ...predicate.GrokVideoJob) *GrokVideoJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GrokVideoJobUpdateOne) Select(field string, fields ...string) *GrokVideoJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GrokVideoJob entity.
func (_u *GrokVideoJobUpdateOne) Save(ctx context.Context) (*GrokVideoJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GrokVideoJobUpdateOne) SaveX(ctx context.Context) *GrokVideoJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GrokVideoJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GrokVideoJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GrokVideoJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := grokvideojob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GrokVideoJobUpdateOne) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := grokvideojob.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "GrokVideoJob.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromptPreview(); ok {
		if err := grokvideojob.PromptPreviewValidator(v); err != nil {
			return &ValidationError{Name: "prompt_preview", err: fmt.Errorf(`ent: validator failed for field "GrokVideoJob.prompt_preview": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := grokvideojob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GrokVideoJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProgressText(); ok {
		if err := grokvideojob.ProgressTextValidator(v); err != nil {
			return &ValidationError{Name: "progress_text", err: fmt.Errorf(`ent: validator failed for field "GrokVideoJob.progress_text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorCode(); ok {
		if err := grokvideojob.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "GrokVideoJob.last_error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *GrokVideoJobUpdateOne) sqlSave(ctx context.Context) (_node *GrokVideoJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grokvideojob.Table, grokvideojob.Columns, sqlgraph.NewFieldSpec(grokvideojob.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GrokVideoJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, grokvideojob.FieldID)
		for _, f := range fields {
			if !grokvideojob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != grokvideojob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(grokvideojob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(grokvideojob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(grokvideojob.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(grokvideojob.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(grokvideojob.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(grokvideojob.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(grokvideojob.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(grokvideojob.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(grokvideojob.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(grokvideojob.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(grokvideojob.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(grokvideojob.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromptPreview(); ok {
		_spec.SetField(grokvideojob.FieldPromptPreview, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(grokvideojob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProgressPercent(); ok {
		_spec.SetField(grokvideojob.FieldProgressPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgressPercent(); ok {
		_spec.AddField(grokvideojob.FieldProgressPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProgressText(); ok {
		_spec.SetField(grokvideojob.FieldProgressText, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResultURL(); ok {
		_spec.SetField(grokvideojob.FieldResultURL, field.TypeString, value)
	}
	if _u.mutation.ResultURLCleared() {
		_spec.ClearField(grokvideojob.FieldResultURL, field.TypeString)
	}
	if value, ok := _u.mutation.ResultUrls(); ok {
		_spec.SetField(grokvideojob.FieldResultUrls, field.TypeString, value)
	}
	if _u.mutation.ResultUrlsCleared() {
		_spec.ClearField(grokvideojob.FieldResultUrls, field.TypeString)
	}
	if value, ok := _u.mutation.CoverImageURL(); ok {
		_spec.SetField(grokvideojob.FieldCoverImageURL, field.TypeString, value)
	}
	if _u.mutation.CoverImageURLCleared() {
		_spec.ClearField(grokvideojob.FieldCoverImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(grokvideojob.FieldLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastErrorCodeCleared() {
		_spec.ClearField(grokvideojob.FieldLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorMessage(); ok {
		_spec.SetField(grokvideojob.FieldLastErrorMessage, field.TypeString, value)
	}
	if _u.mutation.LastErrorMessageCleared() {
		_spec.ClearField(grokvideojob.FieldLastErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(grokvideojob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(grokvideojob.FieldSubmittedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastPolledAt(); ok {
		_spec.SetField(grokvideojob.FieldLastPolledAt, field.TypeTime, value)
	}
	if _u.mutation.LastPolledAtCleared() {
		_spec.ClearField(grokvideojob.FieldLastPolledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(grokvideojob.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(grokvideojob.FieldFinishedAt, field.TypeTime)
	}
	_node = &GrokVideoJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grokvideojob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
