// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grokvideojob"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GrokVideoJobQuery is the builder for querying GrokVideoJob entities.
type GrokVideoJobQuery struct {
	config
	ctx        *QueryContext
	order      []grokvideojob.OrderOption
	inters     []Interceptor
	predicates []predicate.GrokVideoJob
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GrokVideoJobQuery builder.
func (_q *GrokVideoJobQuery) Where(ps ...predicate.GrokVideoJob) *GrokVideoJobQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *GrokVideoJobQuery) Limit(limit int) *GrokVideoJobQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *GrokVideoJobQuery) Offset(offset int) *GrokVideoJobQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *GrokVideoJobQuery) Unique(unique bool) *GrokVideoJobQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *GrokVideoJobQuery) Order(o ...grokvideojob.OrderOption) *GrokVideoJobQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first GrokVideoJob entity from the query.
// Returns a *NotFoundError when no GrokVideoJob was found.
func (_q *GrokVideoJobQuery) First(ctx context.Context) (*GrokVideoJob, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{grokvideojob.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *GrokVideoJobQuery) FirstX(ctx context.Context) *GrokVideoJob {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GrokVideoJob ID from the query.
// Returns a *NotFoundError when no GrokVideoJob ID was found.
func (_q *GrokVideoJobQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{grokvideojob.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *GrokVideoJobQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GrokVideoJob entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GrokVideoJob entity is found.
// Returns a *NotFoundError when no GrokVideoJob entities are found.
func (_q *GrokVideoJobQuery) Only(ctx context.Context) (*GrokVideoJob, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{grokvideojob.Label}
	default:
		return nil, &NotSingularError{grokvideojob.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *GrokVideoJobQuery) OnlyX(ctx context.Context) *GrokVideoJob {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GrokVideoJob ID in the query.
// Returns a *NotSingularError when more than one GrokVideoJob ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *GrokVideoJobQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{grokvideojob.Label}
	default:
		err = &NotSingularError{grokvideojob.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *GrokVideoJobQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GrokVideoJobs.
func (_q *GrokVideoJobQuery) All(ctx context.Context) ([]*GrokVideoJob, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GrokVideoJob, *GrokVideoJobQuery]()
	return withInterceptors[[]*GrokVideoJob](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *GrokVideoJobQuery) AllX(ctx context.Context) []*GrokVideoJob {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GrokVideoJob IDs.
func (_q *GrokVideoJobQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(grokvideojob.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *GrokVideoJobQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *GrokVideoJobQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*GrokVideoJobQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *GrokVideoJobQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *GrokVideoJobQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *GrokVideoJobQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GrokVideoJobQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *GrokVideoJobQuery) Clone() *GrokVideoJobQuery {
	if _q == nil {
		return nil
	}
	return &GrokVideoJobQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]grokvideojob.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.GrokVideoJob{}, _q.predicates...),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RequestID string `json:"request_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GrokVideoJob.Query().
//		GroupBy(grokvideojob.FieldRequestID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *GrokVideoJobQuery) GroupBy(field string, fields ...string) *GrokVideoJobGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GrokVideoJobGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = grokvideojob.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RequestID string `json:"request_id,omitempty"`
//	}
//
//	client.GrokVideoJob.Query().
//		Select(grokvideojob.FieldRequestID).
//		Scan(ctx, &v)
func (_q *GrokVideoJobQuery) Select(fields ...string) *GrokVideoJobSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &GrokVideoJobSelect{GrokVideoJobQuery: _q}
	sbuild.label = grokvideojob.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GrokVideoJobSelect configured with the given aggregations.
func (_q *GrokVideoJobQuery) Aggregate(fns ...AggregateFunc) *GrokVideoJobSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *GrokVideoJobQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !grokvideojob.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *GrokVideoJobQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GrokVideoJob, error) {
	var (
		nodes = []*GrokVideoJob{}
		_spec = _q.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GrokVideoJob).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GrokVideoJob{config: _q.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (_q *GrokVideoJobQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *GrokVideoJobQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(grokvideojob.Table, grokvideojob.Columns, sqlgraph.NewFieldSpec(grokvideojob.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, grokvideojob.FieldID)
		for i := range fields {
			if fields[i] != grokvideojob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *GrokVideoJobQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(grokvideojob.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = grokvideojob.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *GrokVideoJobQuery) ForUpdate(opts ...sql.LockOption) *GrokVideoJobQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *GrokVideoJobQuery) ForShare(opts ...sql.LockOption) *GrokVideoJobQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// GrokVideoJobGroupBy is the group-by builder for GrokVideoJob entities.
type GrokVideoJobGroupBy struct {
	selector
	build *GrokVideoJobQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *GrokVideoJobGroupBy) Aggregate(fns ...AggregateFunc) *GrokVideoJobGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *GrokVideoJobGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GrokVideoJobQuery, *GrokVideoJobGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *GrokVideoJobGroupBy) sqlScan(ctx context.Context, root *GrokVideoJobQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GrokVideoJobSelect is the builder for selecting fields of GrokVideoJob entities.
type GrokVideoJobSelect struct {
	*GrokVideoJobQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *GrokVideoJobSelect) Aggregate(fns ...AggregateFunc) *GrokVideoJobSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *GrokVideoJobSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GrokVideoJobQuery, *GrokVideoJobSelect](ctx, _s.GrokVideoJobQuery, _s, _s.inters, v)
}

func (_s *GrokVideoJobSelect) sqlScan(ctx context.Context, root *GrokVideoJobQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
