// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grokvideojob"
)

// GrokVideoJobCreate is the builder for creating a GrokVideoJob entity.
type GrokVideoJobCreate struct {
	config
	mutation *GrokVideoJobMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRequestID sets the "request_id" field.
func (_c *GrokVideoJobCreate) SetRequestID(v string) *GrokVideoJobCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *GrokVideoJobCreate) SetUserID(v int64) *GrokVideoJobCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *GrokVideoJobCreate) SetAPIKeyID(v int64) *GrokVideoJobCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableAPIKeyID(v *int64) *GrokVideoJobCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *GrokVideoJobCreate) SetGroupID(v int64) *GrokVideoJobCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableGroupID(v *int64) *GrokVideoJobCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *GrokVideoJobCreate) SetAccountID(v int64) *GrokVideoJobCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableAccountID(v *int64) *GrokVideoJobCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *GrokVideoJobCreate) SetModel(v string) *GrokVideoJobCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableModel(v *string) *GrokVideoJobCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetPromptPreview sets the "prompt_preview" field.
func (_c *GrokVideoJobCreate) SetPromptPreview(v string) *GrokVideoJobCreate {
	_c.mutation.SetPromptPreview(v)
	return _c
}

// SetNillablePromptPreview sets the "prompt_preview" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillablePromptPreview(v *string) *GrokVideoJobCreate {
	if v != nil {
		_c.SetPromptPreview(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *GrokVideoJobCreate) SetStatus(v string) *GrokVideoJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableStatus(v *string) *GrokVideoJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProgressPercent sets the "progress_percent" field.
func (_c *GrokVideoJobCreate) SetProgressPercent(v int) *GrokVideoJobCreate {
	_c.mutation.SetProgressPercent(v)
	return _c
}

// SetNillableProgressPercent sets the "progress_percent" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableProgressPercent(v *int) *GrokVideoJobCreate {
	if v != nil {
		_c.SetProgressPercent(*v)
	}
	return _c
}

// SetProgressText sets the "progress_text" field.
func (_c *GrokVideoJobCreate) SetProgressText(v string) *GrokVideoJobCreate {
	_c.mutation.SetProgressText(v)
	return _c
}

// SetNillableProgressText sets the "progress_text" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableProgressText(v *string) *GrokVideoJobCreate {
	if v != nil {
		_c.SetProgressText(*v)
	}
	return _c
}

// SetResultURL sets the "result_url" field.
func (_c *GrokVideoJobCreate) SetResultURL(v string) *GrokVideoJobCreate {
	_c.mutation.SetResultURL(v)
	return _c
}

// SetNillableResultURL sets the "result_url" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableResultURL(v *string) *GrokVideoJobCreate {
	if v != nil {
		_c.SetResultURL(*v)
	}
	return _c
}

// SetResultUrls sets the "result_urls" field.
func (_c *GrokVideoJobCreate) SetResultUrls(v string) *GrokVideoJobCreate {
	_c.mutation.SetResultUrls(v)
	return _c
}

// SetNillableResultUrls sets the "result_urls" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableResultUrls(v *string) *GrokVideoJobCreate {
	if v != nil {
		_c.SetResultUrls(*v)
	}
	return _c
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_c *GrokVideoJobCreate) SetCoverImageURL(v string) *GrokVideoJobCreate {
	_c.mutation.SetCoverImageURL(v)
	return _c
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableCoverImageURL(v *string) *GrokVideoJobCreate {
	if v != nil {
		_c.SetCoverImageURL(*v)
	}
	return _c
}

// SetLastErrorCode sets the "last_error_code" field.
func (_c *GrokVideoJobCreate) SetLastErrorCode(v string) *GrokVideoJobCreate {
	_c.mutation.SetLastErrorCode(v)
	return _c
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableLastErrorCode(v *string) *GrokVideoJobCreate {
	if v != nil {
		_c.SetLastErrorCode(*v)
	}
	return _c
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_c *GrokVideoJobCreate) SetLastErrorMessage(v string) *GrokVideoJobCreate {
	_c.mutation.SetLastErrorMessage(v)
	return _c
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableLastErrorMessage(v *string) *GrokVideoJobCreate {
	if v != nil {
		_c.SetLastErrorMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GrokVideoJobCreate) SetCreatedAt(v time.Time) *GrokVideoJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableCreatedAt(v *time.Time) *GrokVideoJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GrokVideoJobCreate) SetUpdatedAt(v time.Time) *GrokVideoJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableUpdatedAt(v *time.Time) *GrokVideoJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSubmittedAt sets the "submitted_at" field.
func (_c *GrokVideoJobCreate) SetSubmittedAt(v time.Time) *GrokVideoJobCreate {
	_c.mutation.SetSubmittedAt(v)
	return _c
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableSubmittedAt(v *time.Time) *GrokVideoJobCreate {
	if v != nil {
		_c.SetSubmittedAt(*v)
	}
	return _c
}

// SetLastPolledAt sets the "last_polled_at" field.
func (_c *GrokVideoJobCreate) SetLastPolledAt(v time.Time) *GrokVideoJobCreate {
	_c.mutation.SetLastPolledAt(v)
	return _c
}

// SetNillableLastPolledAt sets the "last_polled_at" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableLastPolledAt(v *time.Time) *GrokVideoJobCreate {
	if v != nil {
		_c.SetLastPolledAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *GrokVideoJobCreate) SetFinishedAt(v time.Time) *GrokVideoJobCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *GrokVideoJobCreate) SetNillableFinishedAt(v *time.Time) *GrokVideoJobCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// Mutation returns the GrokVideoJobMutation object of the builder.
func (_c *GrokVideoJobCreate) Mutation() *GrokVideoJobMutation {
	return _c.mutation
}

// Save creates the GrokVideoJob in the database.
func (_c *GrokVideoJobCreate) Save(ctx context.Context) (*GrokVideoJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GrokVideoJobCreate) SaveX(ctx context.Context) *GrokVideoJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GrokVideoJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GrokVideoJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GrokVideoJobCreate) defaults() {
	if _, ok := _c.mutation.Model(); !ok {
		v := grokvideojob.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.PromptPreview(); !ok {
		v := grokvideojob.DefaultPromptPreview
		_c.mutation.SetPromptPreview(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := grokvideojob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ProgressPercent(); !ok {
		v := grokvideojob.DefaultProgressPercent
		_c.mutation.SetProgressPercent(v)
	}
	if _, ok := _c.mutation.ProgressText(); !ok {
		v := grokvideojob.DefaultProgressText
		_c.mutation.SetProgressText(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := grokvideojob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := grokvideojob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SubmittedAt(); !ok {
		v := grokvideojob.DefaultSubmittedAt()
		_c.mutation.SetSubmittedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GrokVideoJobCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "GrokVideoJob.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := grokvideojob.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "GrokVideoJob.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "GrokVideoJob.user_id"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "GrokVideoJob.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := grokvideojob.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "GrokVideoJob.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PromptPreview(); !ok {
		return &ValidationError{Name: "prompt_preview", err: errors.New(`ent: missing required field "GrokVideoJob.prompt_preview"`)}
	}
	if v, ok := _c.mutation.PromptPreview(); ok {
		if err := grokvideojob.PromptPreviewValidator(v); err != nil {
			return &ValidationError{Name: "prompt_preview", err: fmt.Errorf(`ent: validator failed for field "GrokVideoJob.prompt_preview": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "GrokVideoJob.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := grokvideojob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GrokVideoJob.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProgressPercent(); !ok {
		return &ValidationError{Name: "progress_percent", err: errors.New(`ent: missing required field "GrokVideoJob.progress_percent"`)}
	}
	if _, ok := _c.mutation.ProgressText(); !ok {
		return &ValidationError{Name: "progress_text", err: errors.New(`ent: missing required field "GrokVideoJob.progress_text"`)}
	}
	if v, ok := _c.mutation.ProgressText(); ok {
		if err := grokvideojob.ProgressTextValidator(v); err != nil {
			return &ValidationError{Name: "progress_text", err: fmt.Errorf(`ent: validator failed for field "GrokVideoJob.progress_text": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LastErrorCode(); ok {
		if err := grokvideojob.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "GrokVideoJob.last_error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GrokVideoJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GrokVideoJob.updated_at"`)}
	}
	if _, ok := _c.mutation.SubmittedAt(); !ok {
		return &ValidationError{Name: "submitted_at", err: errors.New(`ent: missing required field "GrokVideoJob.submitted_at"`)}
	}
	return nil
}

func (_c *GrokVideoJobCreate) sqlSave(ctx context.Context) (*GrokVideoJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GrokVideoJobCreate) createSpec() (*GrokVideoJob, *sqlgraph.CreateSpec) {
	var (
		_node = &GrokVideoJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(grokvideojob.Table, sqlgraph.NewFieldSpec(grokvideojob.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(grokvideojob.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(grokvideojob.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(grokvideojob.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = &value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(grokvideojob.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(grokvideojob.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(grokvideojob.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.PromptPreview(); ok {
		_spec.SetField(grokvideojob.FieldPromptPreview, field.TypeString, value)
		_node.PromptPreview = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(grokvideojob.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProgressPercent(); ok {
		_spec.SetField(grokvideojob.FieldProgressPercent, field.TypeInt, value)
		_node.ProgressPercent = value
	}
	if value, ok := _c.mutation.ProgressText(); ok {
		_spec.SetField(grokvideojob.FieldProgressText, field.TypeString, value)
		_node.ProgressText = value
	}
	if value, ok := _c.mutation.ResultURL(); ok {
		_spec.SetField(grokvideojob.FieldResultURL, field.TypeString, value)
		_node.ResultURL = &value
	}
	if value, ok := _c.mutation.ResultUrls(); ok {
		_spec.SetField(grokvideojob.FieldResultUrls, field.TypeString, value)
		_node.ResultUrls = &value
	}
	if value, ok := _c.mutation.CoverImageURL(); ok {
		_spec.SetField(grokvideojob.FieldCoverImageURL, field.TypeString, value)
		_node.CoverImageURL = &value
	}
	if value, ok := _c.mutation.LastErrorCode(); ok {
		_spec.SetField(grokvideojob.FieldLastErrorCode, field.TypeString, value)
		_node.LastErrorCode = &value
	}
	if value, ok := _c.mutation.LastErrorMessage(); ok {
		_spec.SetField(grokvideojob.FieldLastErrorMessage, field.TypeString, value)
		_node.LastErrorMessage = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(grokvideojob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(grokvideojob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SubmittedAt(); ok {
		_spec.SetField(grokvideojob.FieldSubmittedAt, field.TypeTime, value)
		_node.SubmittedAt = value
	}
	if value, ok := _c.mutation.LastPolledAt(); ok {
		_spec.SetField(grokvideojob.FieldLastPolledAt, field.TypeTime, value)
		_node.LastPolledAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(grokvideojob.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GrokVideoJob.Create().
//		SetRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GrokVideoJobUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *GrokVideoJobCreate) OnConflict(opts ...sql.ConflictOption) *GrokVideoJobUpsertOne {
	_c.conflict = opts
	return &GrokVideoJobUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GrokVideoJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GrokVideoJobCreate) OnConflictColumns(columns ...string) *GrokVideoJobUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GrokVideoJobUpsertOne{
		create: _c,
	}
}

type (
	// GrokVideoJobUpsertOne is the builder for "upsert"-ing
	//  one GrokVideoJob node.
	GrokVideoJobUpsertOne struct {
		create *GrokVideoJobCreate
	}

	// GrokVideoJobUpsert is the "OnConflict" setter.
	GrokVideoJobUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *GrokVideoJobUpsert) SetUserID(v int64) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateUserID() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *GrokVideoJobUpsert) AddUserID(v int64) *GrokVideoJobUpsert {
	u.Add(grokvideojob.FieldUserID, v)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *GrokVideoJobUpsert) SetAPIKeyID(v int64) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateAPIKeyID() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *GrokVideoJobUpsert) AddAPIKeyID(v int64) *GrokVideoJobUpsert {
	u.Add(grokvideojob.FieldAPIKeyID, v)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *GrokVideoJobUpsert) ClearAPIKeyID() *GrokVideoJobUpsert {
	u.SetNull(grokvideojob.FieldAPIKeyID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GrokVideoJobUpsert) SetGroupID(v int64) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateGroupID() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *GrokVideoJobUpsert) AddGroupID(v int64) *GrokVideoJobUpsert {
	u.Add(grokvideojob.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *GrokVideoJobUpsert) ClearGroupID() *GrokVideoJobUpsert {
	u.SetNull(grokvideojob.FieldGroupID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *GrokVideoJobUpsert) SetAccountID(v int64) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateAccountID() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *GrokVideoJobUpsert) AddAccountID(v int64) *GrokVideoJobUpsert {
	u.Add(grokvideojob.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *GrokVideoJobUpsert) ClearAccountID() *GrokVideoJobUpsert {
	u.SetNull(grokvideojob.FieldAccountID)
	return u
}

// SetModel sets the "model" field.
func (u *GrokVideoJobUpsert) SetModel(v string) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateModel() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldModel)
	return u
}

// SetPromptPreview sets the "prompt_preview" field.
func (u *GrokVideoJobUpsert) SetPromptPreview(v string) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldPromptPreview, v)
	return u
}

// UpdatePromptPreview sets the "prompt_preview" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdatePromptPreview() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldPromptPreview)
	return u
}

// SetStatus sets the "status" field.
func (u *GrokVideoJobUpsert) SetStatus(v string) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateStatus() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldStatus)
	return u
}

// SetProgressPercent sets the "progress_percent" field.
func (u *GrokVideoJobUpsert) SetProgressPercent(v int) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldProgressPercent, v)
	return u
}

// UpdateProgressPercent sets the "progress_percent" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateProgressPercent() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldProgressPercent)
	return u
}

// AddProgressPercent adds v to the "progress_percent" field.
func (u *GrokVideoJobUpsert) AddProgressPercent(v int) *GrokVideoJobUpsert {
	u.Add(grokvideojob.FieldProgressPercent, v)
	return u
}

// SetProgressText sets the "progress_text" field.
func (u *GrokVideoJobUpsert) SetProgressText(v string) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldProgressText, v)
	return u
}

// UpdateProgressText sets the "progress_text" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateProgressText() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldProgressText)
	return u
}

// SetResultURL sets the "result_url" field.
func (u *GrokVideoJobUpsert) SetResultURL(v string) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldResultURL, v)
	return u
}

// UpdateResultURL sets the "result_url" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateResultURL() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldResultURL)
	return u
}

// ClearResultURL clears the value of the "result_url" field.
func (u *GrokVideoJobUpsert) ClearResultURL() *GrokVideoJobUpsert {
	u.SetNull(grokvideojob.FieldResultURL)
	return u
}

// SetResultUrls sets the "result_urls" field.
func (u *GrokVideoJobUpsert) SetResultUrls(v string) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldResultUrls, v)
	return u
}

// UpdateResultUrls sets the "result_urls" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateResultUrls() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldResultUrls)
	return u
}

// ClearResultUrls clears the value of the "result_urls" field.
func (u *GrokVideoJobUpsert) ClearResultUrls() *GrokVideoJobUpsert {
	u.SetNull(grokvideojob.FieldResultUrls)
	return u
}

// SetCoverImageURL sets the "cover_image_url" field.
func (u *GrokVideoJobUpsert) SetCoverImageURL(v string) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldCoverImageURL, v)
	return u
}

// UpdateCoverImageURL sets the "cover_image_url" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateCoverImageURL() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldCoverImageURL)
	return u
}

// ClearCoverImageURL clears the value of the "cover_image_url" field.
func (u *GrokVideoJobUpsert) ClearCoverImageURL() *GrokVideoJobUpsert {
	u.SetNull(grokvideojob.FieldCoverImageURL)
	return u
}

// SetLastErrorCode sets the "last_error_code" field.
func (u *GrokVideoJobUpsert) SetLastErrorCode(v string) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldLastErrorCode, v)
	return u
}

// UpdateLastErrorCode sets the "last_error_code" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateLastErrorCode() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldLastErrorCode)
	return u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (u *GrokVideoJobUpsert) ClearLastErrorCode() *GrokVideoJobUpsert {
	u.SetNull(grokvideojob.FieldLastErrorCode)
	return u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (u *GrokVideoJobUpsert) SetLastErrorMessage(v string) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldLastErrorMessage, v)
	return u
}

// UpdateLastErrorMessage sets the "last_error_message" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateLastErrorMessage() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldLastErrorMessage)
	return u
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (u *GrokVideoJobUpsert) ClearLastErrorMessage() *GrokVideoJobUpsert {
	u.SetNull(grokvideojob.FieldLastErrorMessage)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GrokVideoJobUpsert) SetUpdatedAt(v time.Time) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateUpdatedAt() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldUpdatedAt)
	return u
}

// SetSubmittedAt sets the "submitted_at" field.
func (u *GrokVideoJobUpsert) SetSubmittedAt(v time.Time) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldSubmittedAt, v)
	return u
}

// UpdateSubmittedAt sets the "submitted_at" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateSubmittedAt() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldSubmittedAt)
	return u
}

// SetLastPolledAt sets the "last_polled_at" field.
func (u *GrokVideoJobUpsert) SetLastPolledAt(v time.Time) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldLastPolledAt, v)
	return u
}

// UpdateLastPolledAt sets the "last_polled_at" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateLastPolledAt() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldLastPolledAt)
	return u
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (u *GrokVideoJobUpsert) ClearLastPolledAt() *GrokVideoJobUpsert {
	u.SetNull(grokvideojob.FieldLastPolledAt)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *GrokVideoJobUpsert) SetFinishedAt(v time.Time) *GrokVideoJobUpsert {
	u.Set(grokvideojob.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *GrokVideoJobUpsert) UpdateFinishedAt() *GrokVideoJobUpsert {
	u.SetExcluded(grokvideojob.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *GrokVideoJobUpsert) ClearFinishedAt() *GrokVideoJobUpsert {
	u.SetNull(grokvideojob.FieldFinishedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GrokVideoJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GrokVideoJobUpsertOne) UpdateNewValues() *GrokVideoJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.RequestID(); exists {
			s.SetIgnore(grokvideojob.FieldRequestID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(grokvideojob.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GrokVideoJob.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GrokVideoJobUpsertOne) Ignore() *GrokVideoJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GrokVideoJobUpsertOne) DoNothing() *GrokVideoJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GrokVideoJobCreate.OnConflict
// documentation for more info.
func (u *GrokVideoJobUpsertOne) Update(set func(*GrokVideoJobUpsert)) *GrokVideoJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GrokVideoJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *GrokVideoJobUpsertOne) SetUserID(v int64) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *GrokVideoJobUpsertOne) AddUserID(v int64) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateUserID() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *GrokVideoJobUpsertOne) SetAPIKeyID(v int64) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *GrokVideoJobUpsertOne) AddAPIKeyID(v int64) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateAPIKeyID() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *GrokVideoJobUpsertOne) ClearAPIKeyID() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GrokVideoJobUpsertOne) SetGroupID(v int64) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *GrokVideoJobUpsertOne) AddGroupID(v int64) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateGroupID() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *GrokVideoJobUpsertOne) ClearGroupID() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *GrokVideoJobUpsertOne) SetAccountID(v int64) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *GrokVideoJobUpsertOne) AddAccountID(v int64) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateAccountID() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *GrokVideoJobUpsertOne) ClearAccountID() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearAccountID()
	})
}

// SetModel sets the "model" field.
func (u *GrokVideoJobUpsertOne) SetModel(v string) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateModel() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateModel()
	})
}

// SetPromptPreview sets the "prompt_preview" field.
func (u *GrokVideoJobUpsertOne) SetPromptPreview(v string) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetPromptPreview(v)
	})
}

// UpdatePromptPreview sets the "prompt_preview" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdatePromptPreview() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdatePromptPreview()
	})
}

// SetStatus sets the "status" field.
func (u *GrokVideoJobUpsertOne) SetStatus(v string) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateStatus() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateStatus()
	})
}

// SetProgressPercent sets the "progress_percent" field.
func (u *GrokVideoJobUpsertOne) SetProgressPercent(v int) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetProgressPercent(v)
	})
}

// AddProgressPercent adds v to the "progress_percent" field.
func (u *GrokVideoJobUpsertOne) AddProgressPercent(v int) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.AddProgressPercent(v)
	})
}

// UpdateProgressPercent sets the "progress_percent" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateProgressPercent() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateProgressPercent()
	})
}

// SetProgressText sets the "progress_text" field.
func (u *GrokVideoJobUpsertOne) SetProgressText(v string) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetProgressText(v)
	})
}

// UpdateProgressText sets the "progress_text" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateProgressText() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateProgressText()
	})
}

// SetResultURL sets the "result_url" field.
func (u *GrokVideoJobUpsertOne) SetResultURL(v string) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetResultURL(v)
	})
}

// UpdateResultURL sets the "result_url" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateResultURL() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateResultURL()
	})
}

// ClearResultURL clears the value of the "result_url" field.
func (u *GrokVideoJobUpsertOne) ClearResultURL() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearResultURL()
	})
}

// SetResultUrls sets the "result_urls" field.
func (u *GrokVideoJobUpsertOne) SetResultUrls(v string) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetResultUrls(v)
	})
}

// UpdateResultUrls sets the "result_urls" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateResultUrls() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateResultUrls()
	})
}

// ClearResultUrls clears the value of the "result_urls" field.
func (u *GrokVideoJobUpsertOne) ClearResultUrls() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearResultUrls()
	})
}

// SetCoverImageURL sets the "cover_image_url" field.
func (u *GrokVideoJobUpsertOne) SetCoverImageURL(v string) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetCoverImageURL(v)
	})
}

// UpdateCoverImageURL sets the "cover_image_url" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateCoverImageURL() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateCoverImageURL()
	})
}

// ClearCoverImageURL clears the value of the "cover_image_url" field.
func (u *GrokVideoJobUpsertOne) ClearCoverImageURL() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearCoverImageURL()
	})
}

// SetLastErrorCode sets the "last_error_code" field.
func (u *GrokVideoJobUpsertOne) SetLastErrorCode(v string) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetLastErrorCode(v)
	})
}

// UpdateLastErrorCode sets the "last_error_code" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateLastErrorCode() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateLastErrorCode()
	})
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (u *GrokVideoJobUpsertOne) ClearLastErrorCode() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearLastErrorCode()
	})
}

// SetLastErrorMessage sets the "last_error_message" field.
func (u *GrokVideoJobUpsertOne) SetLastErrorMessage(v string) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetLastErrorMessage(v)
	})
}

// UpdateLastErrorMessage sets the "last_error_message" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateLastErrorMessage() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateLastErrorMessage()
	})
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (u *GrokVideoJobUpsertOne) ClearLastErrorMessage() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearLastErrorMessage()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GrokVideoJobUpsertOne) SetUpdatedAt(v time.Time) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateUpdatedAt() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSubmittedAt sets the "submitted_at" field.
func (u *GrokVideoJobUpsertOne) SetSubmittedAt(v time.Time) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetSubmittedAt(v)
	})
}

// UpdateSubmittedAt sets the "submitted_at" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateSubmittedAt() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateSubmittedAt()
	})
}

// SetLastPolledAt sets the "last_polled_at" field.
func (u *GrokVideoJobUpsertOne) SetLastPolledAt(v time.Time) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetLastPolledAt(v)
	})
}

// UpdateLastPolledAt sets the "last_polled_at" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateLastPolledAt() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateLastPolledAt()
	})
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (u *GrokVideoJobUpsertOne) ClearLastPolledAt() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearLastPolledAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *GrokVideoJobUpsertOne) SetFinishedAt(v time.Time) *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *GrokVideoJobUpsertOne) UpdateFinishedAt() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *GrokVideoJobUpsertOne) ClearFinishedAt() *GrokVideoJobUpsertOne {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearFinishedAt()
	})
}

// Exec executes the query.
func (u *GrokVideoJobUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GrokVideoJobCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GrokVideoJobUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GrokVideoJobUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GrokVideoJobUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GrokVideoJobCreateBulk is the builder for creating many GrokVideoJob entities in bulk.
type GrokVideoJobCreateBulk struct {
	config
	err      error
	builders []*GrokVideoJobCreate
	conflict []sql.ConflictOption
}

// Save creates the GrokVideoJob entities in the database.
func (_c *GrokVideoJobCreateBulk) Save(ctx context.Context) ([]*GrokVideoJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GrokVideoJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GrokVideoJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GrokVideoJobCreateBulk) SaveX(ctx context.Context) []*GrokVideoJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GrokVideoJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GrokVideoJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GrokVideoJob.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GrokVideoJobUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *GrokVideoJobCreateBulk) OnConflict(opts ...sql.ConflictOption) *GrokVideoJobUpsertBulk {
	_c.conflict = opts
	return &GrokVideoJobUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GrokVideoJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GrokVideoJobCreateBulk) OnConflictColumns(columns ...string) *GrokVideoJobUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GrokVideoJobUpsertBulk{
		create: _c,
	}
}

// GrokVideoJobUpsertBulk is the builder for "upsert"-ing
// a bulk of GrokVideoJob nodes.
type GrokVideoJobUpsertBulk struct {
	create *GrokVideoJobCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GrokVideoJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GrokVideoJobUpsertBulk) UpdateNewValues() *GrokVideoJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.RequestID(); exists {
				s.SetIgnore(grokvideojob.FieldRequestID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(grokvideojob.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GrokVideoJob.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GrokVideoJobUpsertBulk) Ignore() *GrokVideoJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GrokVideoJobUpsertBulk) DoNothing() *GrokVideoJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GrokVideoJobCreateBulk.OnConflict
// documentation for more info.
func (u *GrokVideoJobUpsertBulk) Update(set func(*GrokVideoJobUpsert)) *GrokVideoJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GrokVideoJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *GrokVideoJobUpsertBulk) SetUserID(v int64) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *GrokVideoJobUpsertBulk) AddUserID(v int64) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateUserID() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *GrokVideoJobUpsertBulk) SetAPIKeyID(v int64) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *GrokVideoJobUpsertBulk) AddAPIKeyID(v int64) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateAPIKeyID() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *GrokVideoJobUpsertBulk) ClearAPIKeyID() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GrokVideoJobUpsertBulk) SetGroupID(v int64) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *GrokVideoJobUpsertBulk) AddGroupID(v int64) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateGroupID() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *GrokVideoJobUpsertBulk) ClearGroupID() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *GrokVideoJobUpsertBulk) SetAccountID(v int64) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *GrokVideoJobUpsertBulk) AddAccountID(v int64) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateAccountID() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *GrokVideoJobUpsertBulk) ClearAccountID() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearAccountID()
	})
}

// SetModel sets the "model" field.
func (u *GrokVideoJobUpsertBulk) SetModel(v string) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateModel() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateModel()
	})
}

// SetPromptPreview sets the "prompt_preview" field.
func (u *GrokVideoJobUpsertBulk) SetPromptPreview(v string) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetPromptPreview(v)
	})
}

// UpdatePromptPreview sets the "prompt_preview" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdatePromptPreview() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdatePromptPreview()
	})
}

// SetStatus sets the "status" field.
func (u *GrokVideoJobUpsertBulk) SetStatus(v string) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateStatus() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateStatus()
	})
}

// SetProgressPercent sets the "progress_percent" field.
func (u *GrokVideoJobUpsertBulk) SetProgressPercent(v int) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetProgressPercent(v)
	})
}

// AddProgressPercent adds v to the "progress_percent" field.
func (u *GrokVideoJobUpsertBulk) AddProgressPercent(v int) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.AddProgressPercent(v)
	})
}

// UpdateProgressPercent sets the "progress_percent" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateProgressPercent() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateProgressPercent()
	})
}

// SetProgressText sets the "progress_text" field.
func (u *GrokVideoJobUpsertBulk) SetProgressText(v string) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetProgressText(v)
	})
}

// UpdateProgressText sets the "progress_text" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateProgressText() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateProgressText()
	})
}

// SetResultURL sets the "result_url" field.
func (u *GrokVideoJobUpsertBulk) SetResultURL(v string) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetResultURL(v)
	})
}

// UpdateResultURL sets the "result_url" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateResultURL() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateResultURL()
	})
}

// ClearResultURL clears the value of the "result_url" field.
func (u *GrokVideoJobUpsertBulk) ClearResultURL() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearResultURL()
	})
}

// SetResultUrls sets the "result_urls" field.
func (u *GrokVideoJobUpsertBulk) SetResultUrls(v string) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetResultUrls(v)
	})
}

// UpdateResultUrls sets the "result_urls" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateResultUrls() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateResultUrls()
	})
}

// ClearResultUrls clears the value of the "result_urls" field.
func (u *GrokVideoJobUpsertBulk) ClearResultUrls() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearResultUrls()
	})
}

// SetCoverImageURL sets the "cover_image_url" field.
func (u *GrokVideoJobUpsertBulk) SetCoverImageURL(v string) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetCoverImageURL(v)
	})
}

// UpdateCoverImageURL sets the "cover_image_url" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateCoverImageURL() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateCoverImageURL()
	})
}

// ClearCoverImageURL clears the value of the "cover_image_url" field.
func (u *GrokVideoJobUpsertBulk) ClearCoverImageURL() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearCoverImageURL()
	})
}

// SetLastErrorCode sets the "last_error_code" field.
func (u *GrokVideoJobUpsertBulk) SetLastErrorCode(v string) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetLastErrorCode(v)
	})
}

// UpdateLastErrorCode sets the "last_error_code" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateLastErrorCode() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateLastErrorCode()
	})
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (u *GrokVideoJobUpsertBulk) ClearLastErrorCode() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearLastErrorCode()
	})
}

// SetLastErrorMessage sets the "last_error_message" field.
func (u *GrokVideoJobUpsertBulk) SetLastErrorMessage(v string) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetLastErrorMessage(v)
	})
}

// UpdateLastErrorMessage sets the "last_error_message" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateLastErrorMessage() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateLastErrorMessage()
	})
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (u *GrokVideoJobUpsertBulk) ClearLastErrorMessage() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearLastErrorMessage()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GrokVideoJobUpsertBulk) SetUpdatedAt(v time.Time) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateUpdatedAt() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSubmittedAt sets the "submitted_at" field.
func (u *GrokVideoJobUpsertBulk) SetSubmittedAt(v time.Time) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetSubmittedAt(v)
	})
}

// UpdateSubmittedAt sets the "submitted_at" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateSubmittedAt() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateSubmittedAt()
	})
}

// SetLastPolledAt sets the "last_polled_at" field.
func (u *GrokVideoJobUpsertBulk) SetLastPolledAt(v time.Time) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetLastPolledAt(v)
	})
}

// UpdateLastPolledAt sets the "last_polled_at" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateLastPolledAt() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateLastPolledAt()
	})
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (u *GrokVideoJobUpsertBulk) ClearLastPolledAt() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearLastPolledAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *GrokVideoJobUpsertBulk) SetFinishedAt(v time.Time) *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *GrokVideoJobUpsertBulk) UpdateFinishedAt() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *GrokVideoJobUpsertBulk) ClearFinishedAt() *GrokVideoJobUpsertBulk {
	return u.Update(func(s *GrokVideoJobUpsert) {
		s.ClearFinishedAt()
	})
}

// Exec executes the query.
func (u *GrokVideoJobUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GrokVideoJobCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GrokVideoJobCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GrokVideoJobUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
