// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupusertag"
	"github.com/Wei-Shaw/sub2api/ent/usertag"
)

// GroupUserTagCreate is the builder for creating a GroupUserTag entity.
type GroupUserTagCreate struct {
	config
	mutation *GroupUserTagMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetGroupID sets the "group_id" field.
func (_c *GroupUserTagCreate) SetGroupID(v int64) *GroupUserTagCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetTagID sets the "tag_id" field.
func (_c *GroupUserTagCreate) SetTagID(v int64) *GroupUserTagCreate {
	_c.mutation.SetTagID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupUserTagCreate) SetCreatedAt(v time.Time) *GroupUserTagCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupUserTagCreate) SetNillableCreatedAt(v *time.Time) *GroupUserTagCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *GroupUserTagCreate) SetGroup(v *Group) *GroupUserTagCreate {
	return _c.SetGroupID(v.ID)
}

// SetTag sets the "tag" edge to the UserTag entity.
func (_c *GroupUserTagCreate) SetTag(v *UserTag) *GroupUserTagCreate {
	return _c.SetTagID(v.ID)
}

// Mutation returns the GroupUserTagMutation object of the builder.
func (_c *GroupUserTagCreate) Mutation() *GroupUserTagMutation {
	return _c.mutation
}

// Save creates the GroupUserTag in the database.
func (_c *GroupUserTagCreate) Save(ctx context.Context) (*GroupUserTag, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupUserTagCreate) SaveX(ctx context.Context) *GroupUserTag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupUserTagCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupUserTagCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupUserTagCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := groupusertag.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupUserTagCreate) check() error {
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupUserTag.group_id"`)}
	}
	if _, ok := _c.mutation.TagID(); !ok {
		return &ValidationError{Name: "tag_id", err: errors.New(`ent: missing required field "GroupUserTag.tag_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupUserTag.created_at"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "GroupUserTag.group"`)}
	}
	if len(_c.mutation.TagIDs()) == 0 {
		return &ValidationError{Name: "tag", err: errors.New(`ent: missing required edge "GroupUserTag.tag"`)}
	}
	return nil
}

func (_c *GroupUserTagCreate) sqlSave(ctx context.Context) (*GroupUserTag, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *GroupUserTagCreate) createSpec() (*GroupUserTag, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupUserTag{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupusertag.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groupusertag.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupusertag.GroupTable,
			Columns: []string{groupusertag.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupusertag.TagTable,
			Columns: []string{groupusertag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TagID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupUserTag.Create().
//		SetGroupID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupUserTagUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupUserTagCreate) OnConflict(opts ...sql.ConflictOption) *GroupUserTagUpsertOne {
	_c.conflict = opts
	return &GroupUserTagUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupUserTag.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupUserTagCreate) OnConflictColumns(columns ...string) *GroupUserTagUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupUserTagUpsertOne{
		create: _c,
	}
}

type (
	// GroupUserTagUpsertOne is the builder for "upsert"-ing
	//  one GroupUserTag node.
	GroupUserTagUpsertOne struct {
		create *GroupUserTagCreate
	}

	// GroupUserTagUpsert is the "OnConflict" setter.
	GroupUserTagUpsert struct {
		*sql.UpdateSet
	}
)

// SetGroupID sets the "group_id" field.
func (u *GroupUserTagUpsert) SetGroupID(v int64) *GroupUserTagUpsert {
	u.Set(groupusertag.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupUserTagUpsert) UpdateGroupID() *GroupUserTagUpsert {
	u.SetExcluded(groupusertag.FieldGroupID)
	return u
}

// SetTagID sets the "tag_id" field.
func (u *GroupUserTagUpsert) SetTagID(v int64) *GroupUserTagUpsert {
	u.Set(groupusertag.FieldTagID, v)
	return u
}

// UpdateTagID sets the "tag_id" field to the value that was provided on create.
func (u *GroupUserTagUpsert) UpdateTagID() *GroupUserTagUpsert {
	u.SetExcluded(groupusertag.FieldTagID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GroupUserTag.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupUserTagUpsertOne) UpdateNewValues() *GroupUserTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(groupusertag.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupUserTag.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupUserTagUpsertOne) Ignore() *GroupUserTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupUserTagUpsertOne) DoNothing() *GroupUserTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupUserTagCreate.OnConflict
// documentation for more info.
func (u *GroupUserTagUpsertOne) Update(set func(*GroupUserTagUpsert)) *GroupUserTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupUserTagUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupUserTagUpsertOne) SetGroupID(v int64) *GroupUserTagUpsertOne {
	return u.Update(func(s *GroupUserTagUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupUserTagUpsertOne) UpdateGroupID() *GroupUserTagUpsertOne {
	return u.Update(func(s *GroupUserTagUpsert) {
		s.UpdateGroupID()
	})
}

// SetTagID sets the "tag_id" field.
func (u *GroupUserTagUpsertOne) SetTagID(v int64) *GroupUserTagUpsertOne {
	return u.Update(func(s *GroupUserTagUpsert) {
		s.SetTagID(v)
	})
}

// UpdateTagID sets the "tag_id" field to the value that was provided on create.
func (u *GroupUserTagUpsertOne) UpdateTagID() *GroupUserTagUpsertOne {
	return u.Update(func(s *GroupUserTagUpsert) {
		s.UpdateTagID()
	})
}

// Exec executes the query.
func (u *GroupUserTagUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupUserTagCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupUserTagUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// GroupUserTagCreateBulk is the builder for creating many GroupUserTag entities in bulk.
type GroupUserTagCreateBulk struct {
	config
	err      error
	builders []*GroupUserTagCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupUserTag entities in the database.
func (_c *GroupUserTagCreateBulk) Save(ctx context.Context) ([]*GroupUserTag, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupUserTag, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupUserTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupUserTagCreateBulk) SaveX(ctx context.Context) []*GroupUserTag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupUserTagCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupUserTagCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupUserTag.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupUserTagUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupUserTagCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupUserTagUpsertBulk {
	_c.conflict = opts
	return &GroupUserTagUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupUserTag.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupUserTagCreateBulk) OnConflictColumns(columns ...string) *GroupUserTagUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupUserTagUpsertBulk{
		create: _c,
	}
}

// GroupUserTagUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupUserTag nodes.
type GroupUserTagUpsertBulk struct {
	create *GroupUserTagCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupUserTag.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupUserTagUpsertBulk) UpdateNewValues() *GroupUserTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(groupusertag.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupUserTag.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupUserTagUpsertBulk) Ignore() *GroupUserTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupUserTagUpsertBulk) DoNothing() *GroupUserTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupUserTagCreateBulk.OnConflict
// documentation for more info.
func (u *GroupUserTagUpsertBulk) Update(set func(*GroupUserTagUpsert)) *GroupUserTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupUserTagUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupUserTagUpsertBulk) SetGroupID(v int64) *GroupUserTagUpsertBulk {
	return u.Update(func(s *GroupUserTagUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupUserTagUpsertBulk) UpdateGroupID() *GroupUserTagUpsertBulk {
	return u.Update(func(s *GroupUserTagUpsert) {
		s.UpdateGroupID()
	})
}

// SetTagID sets the "tag_id" field.
func (u *GroupUserTagUpsertBulk) SetTagID(v int64) *GroupUserTagUpsertBulk {
	return u.Update(func(s *GroupUserTagUpsert) {
		s.SetTagID(v)
	})
}

// UpdateTagID sets the "tag_id" field to the value that was provided on create.
func (u *GroupUserTagUpsertBulk) UpdateTagID() *GroupUserTagUpsertBulk {
	return u.Update(func(s *GroupUserTagUpsert) {
		s.UpdateTagID()
	})
}

// Exec executes the query.
func (u *GroupUserTagUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupUserTagCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupUserTagCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupUserTagUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
