// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupusertag"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usertag"
)

// GroupUserTagUpdate is the builder for updating GroupUserTag entities.
type GroupUserTagUpdate struct {
	config
	hooks    []Hook
	mutation *GroupUserTagMutation
}

// Where appends a list predicates to the GroupUserTagUpdate builder.
func (_u *GroupUserTagUpdate) Where(ps ...predicate.GroupUserTag) *GroupUserTagUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupUserTagUpdate) SetGroupID(v int64) *GroupUserTagUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupUserTagUpdate) SetNillableGroupID(v *int64) *GroupUserTagUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetTagID sets the "tag_id" field.
func (_u *GroupUserTagUpdate) SetTagID(v int64) *GroupUserTagUpdate {
	_u.mutation.SetTagID(v)
	return _u
}

// SetNillableTagID sets the "tag_id" field if the given value is not nil.
func (_u *GroupUserTagUpdate) SetNillableTagID(v *int64) *GroupUserTagUpdate {
	if v != nil {
		_u.SetTagID(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupUserTagUpdate) SetGroup(v *Group) *GroupUserTagUpdate {
	return _u.SetGroupID(v.ID)
}

// SetTag sets the "tag" edge to the UserTag entity.
func (_u *GroupUserTagUpdate) SetTag(v *UserTag) *GroupUserTagUpdate {
	return _u.SetTagID(v.ID)
}

// Mutation returns the GroupUserTagMutation object of the builder.
func (_u *GroupUserTagUpdate) Mutation() *GroupUserTagMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupUserTagUpdate) ClearGroup() *GroupUserTagUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearTag clears the "tag" edge to the UserTag entity.
func (_u *GroupUserTagUpdate) ClearTag() *GroupUserTagUpdate {
	_u.mutation.ClearTag()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupUserTagUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupUserTagUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupUserTagUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupUserTagUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupUserTagUpdate) check() error {
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupUserTag.group"`)
	}
	if _u.mutation.TagCleared() && len(_u.mutation.TagIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupUserTag.tag"`)
	}
	return nil
}

func (_u *GroupUserTagUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupusertag.Table, groupusertag.Columns, sqlgraph.NewFieldSpec(groupusertag.FieldGroupID, field.TypeInt64), sqlgraph.NewFieldSpec(groupusertag.FieldTagID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupusertag.GroupTable,
			Columns: []string{groupusertag.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupusertag.GroupTable,
			Columns: []string{groupusertag.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupusertag.TagTable,
			Columns: []string{groupusertag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertag.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupusertag.TagTable,
			Columns: []string{groupusertag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupusertag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupUserTagUpdateOne is the builder for updating a single GroupUserTag entity.
type GroupUserTagUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupUserTagMutation
}

// SetGroupID sets the "group_id" field.
func (_u *GroupUserTagUpdateOne) SetGroupID(v int64) *GroupUserTagUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupUserTagUpdateOne) SetNillableGroupID(v *int64) *GroupUserTagUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetTagID sets the "tag_id" field.
func (_u *GroupUserTagUpdateOne) SetTagID(v int64) *GroupUserTagUpdateOne {
	_u.mutation.SetTagID(v)
	return _u
}

// SetNillableTagID sets the "tag_id" field if the given value is not nil.
func (_u *GroupUserTagUpdateOne) SetNillableTagID(v *int64) *GroupUserTagUpdateOne {
	if v != nil {
		_u.SetTagID(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupUserTagUpdateOne) SetGroup(v *Group) *GroupUserTagUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetTag sets the "tag" edge to the UserTag entity.
func (_u *GroupUserTagUpdateOne) SetTag(v *UserTag) *GroupUserTagUpdateOne {
	return _u.SetTagID(v.ID)
}

// Mutation returns the GroupUserTagMutation object of the builder.
func (_u *GroupUserTagUpdateOne) Mutation() *GroupUserTagMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupUserTagUpdateOne) ClearGroup() *GroupUserTagUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearTag clears the "tag" edge to the UserTag entity.
func (_u *GroupUserTagUpdateOne) ClearTag() *GroupUserTagUpdateOne {
	_u.mutation.ClearTag()
	return _u
}

// Where appends a list predicates to the GroupUserTagUpdate builder.
func (_u *GroupUserTagUpdateOne) Where(ps ...predicate.GroupUserTag) *GroupUserTagUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupUserTagUpdateOne) Select(field string, fields ...string) *GroupUserTagUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupUserTag entity.
func (_u *GroupUserTagUpdateOne) Save(ctx context.Context) (*GroupUserTag, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupUserTagUpdateOne) SaveX(ctx context.Context) *GroupUserTag {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupUserTagUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupUserTagUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupUserTagUpdateOne) check() error {
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupUserTag.group"`)
	}
	if _u.mutation.TagCleared() && len(_u.mutation.TagIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupUserTag.tag"`)
	}
	return nil
}

func (_u *GroupUserTagUpdateOne) sqlSave(ctx context.Context) (_node *GroupUserTag, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupusertag.Table, groupusertag.Columns, sqlgraph.NewFieldSpec(groupusertag.FieldGroupID, field.TypeInt64), sqlgraph.NewFieldSpec(groupusertag.FieldTagID, field.TypeInt64))
	if id, ok := _u.mutation.GroupID(); !ok {
		return nil, &ValidationError{Name: "group_id", err: errors.New(`ent: missing "GroupUserTag.group_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.TagID(); !ok {
		return nil, &ValidationError{Name: "tag_id", err: errors.New(`ent: missing "GroupUserTag.tag_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !groupusertag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupusertag.GroupTable,
			Columns: []string{groupusertag.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupusertag.GroupTable,
			Columns: []string{groupusertag.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupusertag.TagTable,
			Columns: []string{groupusertag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertag.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupusertag.TagTable,
			Columns: []string{groupusertag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GroupUserTag{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupusertag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
