// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usertag"
	"github.com/Wei-Shaw/sub2api/ent/usertagassignment"
)

// UserTagAssignment is the model entity for the UserTagAssignment schema.
type UserTagAssignment struct {
	config `json:"-"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// TagID holds the value of the "tag_id" field.
	TagID int64 `json:"tag_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserTagAssignmentQuery when eager-loading is set.
	Edges        UserTagAssignmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserTagAssignmentEdges holds the relations/edges for other nodes in the graph.
type UserTagAssignmentEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Tag holds the value of the tag edge.
	Tag *UserTag `json:"tag,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserTagAssignmentEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// TagOrErr returns the Tag value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserTagAssignmentEdges) TagOrErr() (*UserTag, error) {
	if e.Tag != nil {
		return e.Tag, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: usertag.Label}
	}
	return nil, &NotLoadedError{edge: "tag"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserTagAssignment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usertagassignment.FieldUserID, usertagassignment.FieldTagID:
			values[i] = new(sql.NullInt64)
		case usertagassignment.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserTagAssignment fields.
func (_m *UserTagAssignment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usertagassignment.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case usertagassignment.FieldTagID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tag_id", values[i])
			} else if value.Valid {
				_m.TagID = value.Int64
			}
		case usertagassignment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserTagAssignment.
// This includes values selected through modifiers, order, etc.
func (_m *UserTagAssignment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserTagAssignment entity.
func (_m *UserTagAssignment) QueryUser() *UserQuery {
	return NewUserTagAssignmentClient(_m.config).QueryUser(_m)
}

// QueryTag queries the "tag" edge of the UserTagAssignment entity.
func (_m *UserTagAssignment) QueryTag() *UserTagQuery {
	return NewUserTagAssignmentClient(_m.config).QueryTag(_m)
}

// Update returns a builder for updating this UserTagAssignment.
// Note that you need to call UserTagAssignment.Unwrap() before calling this method if this UserTagAssignment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserTagAssignment) Update() *UserTagAssignmentUpdateOne {
	return NewUserTagAssignmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserTagAssignment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserTagAssignment) Unwrap() *UserTagAssignment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserTagAssignment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserTagAssignment) String() string {
	var builder strings.Builder
	builder.WriteString("UserTagAssignment(")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("tag_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TagID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserTagAssignments is a parsable slice of UserTagAssignment.
type UserTagAssignments []*UserTagAssignment
