// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usertag"
	"github.com/Wei-Shaw/sub2api/ent/usertagassignment"
)

// UserTagAssignmentCreate is the builder for creating a UserTagAssignment entity.
type UserTagAssignmentCreate struct {
	config
	mutation *UserTagAssignmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserTagAssignmentCreate) SetUserID(v int64) *UserTagAssignmentCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTagID sets the "tag_id" field.
func (_c *UserTagAssignmentCreate) SetTagID(v int64) *UserTagAssignmentCreate {
	_c.mutation.SetTagID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserTagAssignmentCreate) SetCreatedAt(v time.Time) *UserTagAssignmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserTagAssignmentCreate) SetNillableCreatedAt(v *time.Time) *UserTagAssignmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserTagAssignmentCreate) SetUser(v *User) *UserTagAssignmentCreate {
	return _c.SetUserID(v.ID)
}

// SetTag sets the "tag" edge to the UserTag entity.
func (_c *UserTagAssignmentCreate) SetTag(v *UserTag) *UserTagAssignmentCreate {
	return _c.SetTagID(v.ID)
}

// Mutation returns the UserTagAssignmentMutation object of the builder.
func (_c *UserTagAssignmentCreate) Mutation() *UserTagAssignmentMutation {
	return _c.mutation
}

// Save creates the UserTagAssignment in the database.
func (_c *UserTagAssignmentCreate) Save(ctx context.Context) (*UserTagAssignment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserTagAssignmentCreate) SaveX(ctx context.Context) *UserTagAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserTagAssignmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserTagAssignmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserTagAssignmentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usertagassignment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserTagAssignmentCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserTagAssignment.user_id"`)}
	}
	if _, ok := _c.mutation.TagID(); !ok {
		return &ValidationError{Name: "tag_id", err: errors.New(`ent: missing required field "UserTagAssignment.tag_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserTagAssignment.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserTagAssignment.user"`)}
	}
	if len(_c.mutation.TagIDs()) == 0 {
		return &ValidationError{Name: "tag", err: errors.New(`ent: missing required edge "UserTagAssignment.tag"`)}
	}
	return nil
}

func (_c *UserTagAssignmentCreate) sqlSave(ctx context.Context) (*UserTagAssignment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *UserTagAssignmentCreate) createSpec() (*UserTagAssignment, *sqlgraph.CreateSpec) {
	var (
		_node = &UserTagAssignment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usertagassignment.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usertagassignment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertagassignment.UserTable,
			Columns: []string{usertagassignment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertagassignment.TagTable,
			Columns: []string{usertagassignment.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TagID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserTagAssignment.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserTagAssignmentUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserTagAssignmentCreate) OnConflict(opts ...sql.ConflictOption) *UserTagAssignmentUpsertOne {
	_c.conflict = opts
	return &UserTagAssignmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserTagAssignment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserTagAssignmentCreate) OnConflictColumns(columns ...string) *UserTagAssignmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserTagAssignmentUpsertOne{
		create: _c,
	}
}

type (
	// UserTagAssignmentUpsertOne is the builder for "upsert"-ing
	//  one UserTagAssignment node.
	UserTagAssignmentUpsertOne struct {
		create *UserTagAssignmentCreate
	}

	// UserTagAssignmentUpsert is the "OnConflict" setter.
	UserTagAssignmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserTagAssignmentUpsert) SetUserID(v int64) *UserTagAssignmentUpsert {
	u.Set(usertagassignment.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserTagAssignmentUpsert) UpdateUserID() *UserTagAssignmentUpsert {
	u.SetExcluded(usertagassignment.FieldUserID)
	return u
}

// SetTagID sets the "tag_id" field.
func (u *UserTagAssignmentUpsert) SetTagID(v int64) *UserTagAssignmentUpsert {
	u.Set(usertagassignment.FieldTagID, v)
	return u
}

// UpdateTagID sets the "tag_id" field to the value that was provided on create.
func (u *UserTagAssignmentUpsert) UpdateTagID() *UserTagAssignmentUpsert {
	u.SetExcluded(usertagassignment.FieldTagID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserTagAssignment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserTagAssignmentUpsertOne) UpdateNewValues() *UserTagAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usertagassignment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserTagAssignment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserTagAssignmentUpsertOne) Ignore() *UserTagAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserTagAssignmentUpsertOne) DoNothing() *UserTagAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserTagAssignmentCreate.OnConflict
// documentation for more info.
func (u *UserTagAssignmentUpsertOne) Update(set func(*UserTagAssignmentUpsert)) *UserTagAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserTagAssignmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserTagAssignmentUpsertOne) SetUserID(v int64) *UserTagAssignmentUpsertOne {
	return u.Update(func(s *UserTagAssignmentUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserTagAssignmentUpsertOne) UpdateUserID() *UserTagAssignmentUpsertOne {
	return u.Update(func(s *UserTagAssignmentUpsert) {
		s.UpdateUserID()
	})
}

// SetTagID sets the "tag_id" field.
func (u *UserTagAssignmentUpsertOne) SetTagID(v int64) *UserTagAssignmentUpsertOne {
	return u.Update(func(s *UserTagAssignmentUpsert) {
		s.SetTagID(v)
	})
}

// UpdateTagID sets the "tag_id" field to the value that was provided on create.
func (u *UserTagAssignmentUpsertOne) UpdateTagID() *UserTagAssignmentUpsertOne {
	return u.Update(func(s *UserTagAssignmentUpsert) {
		s.UpdateTagID()
	})
}

// Exec executes the query.
func (u *UserTagAssignmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserTagAssignmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserTagAssignmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// UserTagAssignmentCreateBulk is the builder for creating many UserTagAssignment entities in bulk.
type UserTagAssignmentCreateBulk struct {
	config
	err      error
	builders []*UserTagAssignmentCreate
	conflict []sql.ConflictOption
}

// Save creates the UserTagAssignment entities in the database.
func (_c *UserTagAssignmentCreateBulk) Save(ctx context.Context) ([]*UserTagAssignment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserTagAssignment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserTagAssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserTagAssignmentCreateBulk) SaveX(ctx context.Context) []*UserTagAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserTagAssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserTagAssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserTagAssignment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserTagAssignmentUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserTagAssignmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserTagAssignmentUpsertBulk {
	_c.conflict = opts
	return &UserTagAssignmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserTagAssignment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserTagAssignmentCreateBulk) OnConflictColumns(columns ...string) *UserTagAssignmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserTagAssignmentUpsertBulk{
		create: _c,
	}
}

// UserTagAssignmentUpsertBulk is the builder for "upsert"-ing
// a bulk of UserTagAssignment nodes.
type UserTagAssignmentUpsertBulk struct {
	create *UserTagAssignmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserTagAssignment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserTagAssignmentUpsertBulk) UpdateNewValues() *UserTagAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usertagassignment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserTagAssignment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserTagAssignmentUpsertBulk) Ignore() *UserTagAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserTagAssignmentUpsertBulk) DoNothing() *UserTagAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserTagAssignmentCreateBulk.OnConflict
// documentation for more info.
func (u *UserTagAssignmentUpsertBulk) Update(set func(*UserTagAssignmentUpsert)) *UserTagAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserTagAssignmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserTagAssignmentUpsertBulk) SetUserID(v int64) *UserTagAssignmentUpsertBulk {
	return u.Update(func(s *UserTagAssignmentUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserTagAssignmentUpsertBulk) UpdateUserID() *UserTagAssignmentUpsertBulk {
	return u.Update(func(s *UserTagAssignmentUpsert) {
		s.UpdateUserID()
	})
}

// SetTagID sets the "tag_id" field.
func (u *UserTagAssignmentUpsertBulk) SetTagID(v int64) *UserTagAssignmentUpsertBulk {
	return u.Update(func(s *UserTagAssignmentUpsert) {
		s.SetTagID(v)
	})
}

// UpdateTagID sets the "tag_id" field to the value that was provided on create.
func (u *UserTagAssignmentUpsertBulk) UpdateTagID() *UserTagAssignmentUpsertBulk {
	return u.Update(func(s *UserTagAssignmentUpsert) {
		s.UpdateTagID()
	})
}

// Exec executes the query.
func (u *UserTagAssignmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserTagAssignmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserTagAssignmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserTagAssignmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
