// Code generated by ent, DO NOT EDIT.

package grokvideojob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldRequestID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldGroupID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldAccountID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldModel, v))
}

// PromptPreview applies equality check predicate on the "prompt_preview" field. It's identical to PromptPreviewEQ.
func PromptPreview(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldPromptPreview, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldStatus, v))
}

// ProgressPercent applies equality check predicate on the "progress_percent" field. It's identical to ProgressPercentEQ.
func ProgressPercent(v int) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldProgressPercent, v))
}

// ProgressText applies equality check predicate on the "progress_text" field. It's identical to ProgressTextEQ.
func ProgressText(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldProgressText, v))
}

// ResultURL applies equality check predicate on the "result_url" field. It's identical to ResultURLEQ.
func ResultURL(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldResultURL, v))
}

// ResultUrls applies equality check predicate on the "result_urls" field. It's identical to ResultUrlsEQ.
func ResultUrls(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldResultUrls, v))
}

// CoverImageURL applies equality check predicate on the "cover_image_url" field. It's identical to CoverImageURLEQ.
func CoverImageURL(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldCoverImageURL, v))
}

// LastErrorCode applies equality check predicate on the "last_error_code" field. It's identical to LastErrorCodeEQ.
func LastErrorCode(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldLastErrorCode, v))
}

// LastErrorMessage applies equality check predicate on the "last_error_message" field. It's identical to LastErrorMessageEQ.
func LastErrorMessage(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldLastErrorMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// SubmittedAt applies equality check predicate on the "submitted_at" field. It's identical to SubmittedAtEQ.
func SubmittedAt(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldSubmittedAt, v))
}

// LastPolledAt applies equality check predicate on the "last_polled_at" field. It's identical to LastPolledAtEQ.
func LastPolledAt(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldLastPolledAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldFinishedAt, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContainsFold(FieldRequestID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldUserID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotNull(FieldAPIKeyID))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotNull(FieldGroupID))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotNull(FieldAccountID))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContainsFold(FieldModel, v))
}

// PromptPreviewEQ applies the EQ predicate on the "prompt_preview" field.
func PromptPreviewEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldPromptPreview, v))
}

// PromptPreviewNEQ applies the NEQ predicate on the "prompt_preview" field.
func PromptPreviewNEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldPromptPreview, v))
}

// PromptPreviewIn applies the In predicate on the "prompt_preview" field.
func PromptPreviewIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldPromptPreview, vs...))
}

// PromptPreviewNotIn applies the NotIn predicate on the "prompt_preview" field.
func PromptPreviewNotIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldPromptPreview, vs...))
}

// PromptPreviewGT applies the GT predicate on the "prompt_preview" field.
func PromptPreviewGT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldPromptPreview, v))
}

// PromptPreviewGTE applies the GTE predicate on the "prompt_preview" field.
func PromptPreviewGTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldPromptPreview, v))
}

// PromptPreviewLT applies the LT predicate on the "prompt_preview" field.
func PromptPreviewLT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldPromptPreview, v))
}

// PromptPreviewLTE applies the LTE predicate on the "prompt_preview" field.
func PromptPreviewLTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldPromptPreview, v))
}

// PromptPreviewContains applies the Contains predicate on the "prompt_preview" field.
func PromptPreviewContains(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContains(FieldPromptPreview, v))
}

// PromptPreviewHasPrefix applies the HasPrefix predicate on the "prompt_preview" field.
func PromptPreviewHasPrefix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasPrefix(FieldPromptPreview, v))
}

// PromptPreviewHasSuffix applies the HasSuffix predicate on the "prompt_preview" field.
func PromptPreviewHasSuffix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasSuffix(FieldPromptPreview, v))
}

// PromptPreviewEqualFold applies the EqualFold predicate on the "prompt_preview" field.
func PromptPreviewEqualFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEqualFold(FieldPromptPreview, v))
}

// PromptPreviewContainsFold applies the ContainsFold predicate on the "prompt_preview" field.
func PromptPreviewContainsFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContainsFold(FieldPromptPreview, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContainsFold(FieldStatus, v))
}

// ProgressPercentEQ applies the EQ predicate on the "progress_percent" field.
func ProgressPercentEQ(v int) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldProgressPercent, v))
}

// ProgressPercentNEQ applies the NEQ predicate on the "progress_percent" field.
func ProgressPercentNEQ(v int) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldProgressPercent, v))
}

// ProgressPercentIn applies the In predicate on the "progress_percent" field.
func ProgressPercentIn(vs ...int) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldProgressPercent, vs...))
}

// ProgressPercentNotIn applies the NotIn predicate on the "progress_percent" field.
func ProgressPercentNotIn(vs ...int) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldProgressPercent, vs...))
}

// ProgressPercentGT applies the GT predicate on the "progress_percent" field.
func ProgressPercentGT(v int) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldProgressPercent, v))
}

// ProgressPercentGTE applies the GTE predicate on the "progress_percent" field.
func ProgressPercentGTE(v int) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldProgressPercent, v))
}

// ProgressPercentLT applies the LT predicate on the "progress_percent" field.
func ProgressPercentLT(v int) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldProgressPercent, v))
}

// ProgressPercentLTE applies the LTE predicate on the "progress_percent" field.
func ProgressPercentLTE(v int) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldProgressPercent, v))
}

// ProgressTextEQ applies the EQ predicate on the "progress_text" field.
func ProgressTextEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldProgressText, v))
}

// ProgressTextNEQ applies the NEQ predicate on the "progress_text" field.
func ProgressTextNEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldProgressText, v))
}

// ProgressTextIn applies the In predicate on the "progress_text" field.
func ProgressTextIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldProgressText, vs...))
}

// ProgressTextNotIn applies the NotIn predicate on the "progress_text" field.
func ProgressTextNotIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldProgressText, vs...))
}

// ProgressTextGT applies the GT predicate on the "progress_text" field.
func ProgressTextGT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldProgressText, v))
}

// ProgressTextGTE applies the GTE predicate on the "progress_text" field.
func ProgressTextGTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldProgressText, v))
}

// ProgressTextLT applies the LT predicate on the "progress_text" field.
func ProgressTextLT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldProgressText, v))
}

// ProgressTextLTE applies the LTE predicate on the "progress_text" field.
func ProgressTextLTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldProgressText, v))
}

// ProgressTextContains applies the Contains predicate on the "progress_text" field.
func ProgressTextContains(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContains(FieldProgressText, v))
}

// ProgressTextHasPrefix applies the HasPrefix predicate on the "progress_text" field.
func ProgressTextHasPrefix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasPrefix(FieldProgressText, v))
}

// ProgressTextHasSuffix applies the HasSuffix predicate on the "progress_text" field.
func ProgressTextHasSuffix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasSuffix(FieldProgressText, v))
}

// ProgressTextEqualFold applies the EqualFold predicate on the "progress_text" field.
func ProgressTextEqualFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEqualFold(FieldProgressText, v))
}

// ProgressTextContainsFold applies the ContainsFold predicate on the "progress_text" field.
func ProgressTextContainsFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContainsFold(FieldProgressText, v))
}

// ResultURLEQ applies the EQ predicate on the "result_url" field.
func ResultURLEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldResultURL, v))
}

// ResultURLNEQ applies the NEQ predicate on the "result_url" field.
func ResultURLNEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldResultURL, v))
}

// ResultURLIn applies the In predicate on the "result_url" field.
func ResultURLIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldResultURL, vs...))
}

// ResultURLNotIn applies the NotIn predicate on the "result_url" field.
func ResultURLNotIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldResultURL, vs...))
}

// ResultURLGT applies the GT predicate on the "result_url" field.
func ResultURLGT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldResultURL, v))
}

// ResultURLGTE applies the GTE predicate on the "result_url" field.
func ResultURLGTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldResultURL, v))
}

// ResultURLLT applies the LT predicate on the "result_url" field.
func ResultURLLT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldResultURL, v))
}

// ResultURLLTE applies the LTE predicate on the "result_url" field.
func ResultURLLTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldResultURL, v))
}

// ResultURLContains applies the Contains predicate on the "result_url" field.
func ResultURLContains(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContains(FieldResultURL, v))
}

// ResultURLHasPrefix applies the HasPrefix predicate on the "result_url" field.
func ResultURLHasPrefix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasPrefix(FieldResultURL, v))
}

// ResultURLHasSuffix applies the HasSuffix predicate on the "result_url" field.
func ResultURLHasSuffix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasSuffix(FieldResultURL, v))
}

// ResultURLIsNil applies the IsNil predicate on the "result_url" field.
func ResultURLIsNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIsNull(FieldResultURL))
}

// ResultURLNotNil applies the NotNil predicate on the "result_url" field.
func ResultURLNotNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotNull(FieldResultURL))
}

// ResultURLEqualFold applies the EqualFold predicate on the "result_url" field.
func ResultURLEqualFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEqualFold(FieldResultURL, v))
}

// ResultURLContainsFold applies the ContainsFold predicate on the "result_url" field.
func ResultURLContainsFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContainsFold(FieldResultURL, v))
}

// ResultUrlsEQ applies the EQ predicate on the "result_urls" field.
func ResultUrlsEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldResultUrls, v))
}

// ResultUrlsNEQ applies the NEQ predicate on the "result_urls" field.
func ResultUrlsNEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldResultUrls, v))
}

// ResultUrlsIn applies the In predicate on the "result_urls" field.
func ResultUrlsIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldResultUrls, vs...))
}

// ResultUrlsNotIn applies the NotIn predicate on the "result_urls" field.
func ResultUrlsNotIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldResultUrls, vs...))
}

// ResultUrlsGT applies the GT predicate on the "result_urls" field.
func ResultUrlsGT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldResultUrls, v))
}

// ResultUrlsGTE applies the GTE predicate on the "result_urls" field.
func ResultUrlsGTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldResultUrls, v))
}

// ResultUrlsLT applies the LT predicate on the "result_urls" field.
func ResultUrlsLT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldResultUrls, v))
}

// ResultUrlsLTE applies the LTE predicate on the "result_urls" field.
func ResultUrlsLTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldResultUrls, v))
}

// ResultUrlsContains applies the Contains predicate on the "result_urls" field.
func ResultUrlsContains(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContains(FieldResultUrls, v))
}

// ResultUrlsHasPrefix applies the HasPrefix predicate on the "result_urls" field.
func ResultUrlsHasPrefix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasPrefix(FieldResultUrls, v))
}

// ResultUrlsHasSuffix applies the HasSuffix predicate on the "result_urls" field.
func ResultUrlsHasSuffix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasSuffix(FieldResultUrls, v))
}

// ResultUrlsIsNil applies the IsNil predicate on the "result_urls" field.
func ResultUrlsIsNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIsNull(FieldResultUrls))
}

// ResultUrlsNotNil applies the NotNil predicate on the "result_urls" field.
func ResultUrlsNotNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotNull(FieldResultUrls))
}

// ResultUrlsEqualFold applies the EqualFold predicate on the "result_urls" field.
func ResultUrlsEqualFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEqualFold(FieldResultUrls, v))
}

// ResultUrlsContainsFold applies the ContainsFold predicate on the "result_urls" field.
func ResultUrlsContainsFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContainsFold(FieldResultUrls, v))
}

// CoverImageURLEQ applies the EQ predicate on the "cover_image_url" field.
func CoverImageURLEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldCoverImageURL, v))
}

// CoverImageURLNEQ applies the NEQ predicate on the "cover_image_url" field.
func CoverImageURLNEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldCoverImageURL, v))
}

// CoverImageURLIn applies the In predicate on the "cover_image_url" field.
func CoverImageURLIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldCoverImageURL, vs...))
}

// CoverImageURLNotIn applies the NotIn predicate on the "cover_image_url" field.
func CoverImageURLNotIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldCoverImageURL, vs...))
}

// CoverImageURLGT applies the GT predicate on the "cover_image_url" field.
func CoverImageURLGT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldCoverImageURL, v))
}

// CoverImageURLGTE applies the GTE predicate on the "cover_image_url" field.
func CoverImageURLGTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldCoverImageURL, v))
}

// CoverImageURLLT applies the LT predicate on the "cover_image_url" field.
func CoverImageURLLT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldCoverImageURL, v))
}

// CoverImageURLLTE applies the LTE predicate on the "cover_image_url" field.
func CoverImageURLLTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldCoverImageURL, v))
}

// CoverImageURLContains applies the Contains predicate on the "cover_image_url" field.
func CoverImageURLContains(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContains(FieldCoverImageURL, v))
}

// CoverImageURLHasPrefix applies the HasPrefix predicate on the "cover_image_url" field.
func CoverImageURLHasPrefix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasPrefix(FieldCoverImageURL, v))
}

// CoverImageURLHasSuffix applies the HasSuffix predicate on the "cover_image_url" field.
func CoverImageURLHasSuffix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasSuffix(FieldCoverImageURL, v))
}

// CoverImageURLIsNil applies the IsNil predicate on the "cover_image_url" field.
func CoverImageURLIsNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIsNull(FieldCoverImageURL))
}

// CoverImageURLNotNil applies the NotNil predicate on the "cover_image_url" field.
func CoverImageURLNotNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotNull(FieldCoverImageURL))
}

// CoverImageURLEqualFold applies the EqualFold predicate on the "cover_image_url" field.
func CoverImageURLEqualFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEqualFold(FieldCoverImageURL, v))
}

// CoverImageURLContainsFold applies the ContainsFold predicate on the "cover_image_url" field.
func CoverImageURLContainsFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContainsFold(FieldCoverImageURL, v))
}

// LastErrorCodeEQ applies the EQ predicate on the "last_error_code" field.
func LastErrorCodeEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldLastErrorCode, v))
}

// LastErrorCodeNEQ applies the NEQ predicate on the "last_error_code" field.
func LastErrorCodeNEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldLastErrorCode, v))
}

// LastErrorCodeIn applies the In predicate on the "last_error_code" field.
func LastErrorCodeIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldLastErrorCode, vs...))
}

// LastErrorCodeNotIn applies the NotIn predicate on the "last_error_code" field.
func LastErrorCodeNotIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldLastErrorCode, vs...))
}

// LastErrorCodeGT applies the GT predicate on the "last_error_code" field.
func LastErrorCodeGT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldLastErrorCode, v))
}

// LastErrorCodeGTE applies the GTE predicate on the "last_error_code" field.
func LastErrorCodeGTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldLastErrorCode, v))
}

// LastErrorCodeLT applies the LT predicate on the "last_error_code" field.
func LastErrorCodeLT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldLastErrorCode, v))
}

// LastErrorCodeLTE applies the LTE predicate on the "last_error_code" field.
func LastErrorCodeLTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldLastErrorCode, v))
}

// LastErrorCodeContains applies the Contains predicate on the "last_error_code" field.
func LastErrorCodeContains(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContains(FieldLastErrorCode, v))
}

// LastErrorCodeHasPrefix applies the HasPrefix predicate on the "last_error_code" field.
func LastErrorCodeHasPrefix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasPrefix(FieldLastErrorCode, v))
}

// LastErrorCodeHasSuffix applies the HasSuffix predicate on the "last_error_code" field.
func LastErrorCodeHasSuffix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasSuffix(FieldLastErrorCode, v))
}

// LastErrorCodeIsNil applies the IsNil predicate on the "last_error_code" field.
func LastErrorCodeIsNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIsNull(FieldLastErrorCode))
}

// LastErrorCodeNotNil applies the NotNil predicate on the "last_error_code" field.
func LastErrorCodeNotNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotNull(FieldLastErrorCode))
}

// LastErrorCodeEqualFold applies the EqualFold predicate on the "last_error_code" field.
func LastErrorCodeEqualFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEqualFold(FieldLastErrorCode, v))
}

// LastErrorCodeContainsFold applies the ContainsFold predicate on the "last_error_code" field.
func LastErrorCodeContainsFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContainsFold(FieldLastErrorCode, v))
}

// LastErrorMessageEQ applies the EQ predicate on the "last_error_message" field.
func LastErrorMessageEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldLastErrorMessage, v))
}

// LastErrorMessageNEQ applies the NEQ predicate on the "last_error_message" field.
func LastErrorMessageNEQ(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldLastErrorMessage, v))
}

// LastErrorMessageIn applies the In predicate on the "last_error_message" field.
func LastErrorMessageIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldLastErrorMessage, vs...))
}

// LastErrorMessageNotIn applies the NotIn predicate on the "last_error_message" field.
func LastErrorMessageNotIn(vs ...string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldLastErrorMessage, vs...))
}

// LastErrorMessageGT applies the GT predicate on the "last_error_message" field.
func LastErrorMessageGT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldLastErrorMessage, v))
}

// LastErrorMessageGTE applies the GTE predicate on the "last_error_message" field.
func LastErrorMessageGTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldLastErrorMessage, v))
}

// LastErrorMessageLT applies the LT predicate on the "last_error_message" field.
func LastErrorMessageLT(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldLastErrorMessage, v))
}

// LastErrorMessageLTE applies the LTE predicate on the "last_error_message" field.
func LastErrorMessageLTE(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldLastErrorMessage, v))
}

// LastErrorMessageContains applies the Contains predicate on the "last_error_message" field.
func LastErrorMessageContains(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContains(FieldLastErrorMessage, v))
}

// LastErrorMessageHasPrefix applies the HasPrefix predicate on the "last_error_message" field.
func LastErrorMessageHasPrefix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasPrefix(FieldLastErrorMessage, v))
}

// LastErrorMessageHasSuffix applies the HasSuffix predicate on the "last_error_message" field.
func LastErrorMessageHasSuffix(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldHasSuffix(FieldLastErrorMessage, v))
}

// LastErrorMessageIsNil applies the IsNil predicate on the "last_error_message" field.
func LastErrorMessageIsNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIsNull(FieldLastErrorMessage))
}

// LastErrorMessageNotNil applies the NotNil predicate on the "last_error_message" field.
func LastErrorMessageNotNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotNull(FieldLastErrorMessage))
}

// LastErrorMessageEqualFold applies the EqualFold predicate on the "last_error_message" field.
func LastErrorMessageEqualFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEqualFold(FieldLastErrorMessage, v))
}

// LastErrorMessageContainsFold applies the ContainsFold predicate on the "last_error_message" field.
func LastErrorMessageContainsFold(v string) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldContainsFold(FieldLastErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// SubmittedAtEQ applies the EQ predicate on the "submitted_at" field.
func SubmittedAtEQ(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldSubmittedAt, v))
}

// SubmittedAtNEQ applies the NEQ predicate on the "submitted_at" field.
func SubmittedAtNEQ(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldSubmittedAt, v))
}

// SubmittedAtIn applies the In predicate on the "submitted_at" field.
func SubmittedAtIn(vs ...time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldSubmittedAt, vs...))
}

// SubmittedAtNotIn applies the NotIn predicate on the "submitted_at" field.
func SubmittedAtNotIn(vs ...time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldSubmittedAt, vs...))
}

// SubmittedAtGT applies the GT predicate on the "submitted_at" field.
func SubmittedAtGT(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldSubmittedAt, v))
}

// SubmittedAtGTE applies the GTE predicate on the "submitted_at" field.
func SubmittedAtGTE(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldSubmittedAt, v))
}

// SubmittedAtLT applies the LT predicate on the "submitted_at" field.
func SubmittedAtLT(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldSubmittedAt, v))
}

// SubmittedAtLTE applies the LTE predicate on the "submitted_at" field.
func SubmittedAtLTE(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldSubmittedAt, v))
}

// LastPolledAtEQ applies the EQ predicate on the "last_polled_at" field.
func LastPolledAtEQ(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldLastPolledAt, v))
}

// LastPolledAtNEQ applies the NEQ predicate on the "last_polled_at" field.
func LastPolledAtNEQ(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldLastPolledAt, v))
}

// LastPolledAtIn applies the In predicate on the "last_polled_at" field.
func LastPolledAtIn(vs ...time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldLastPolledAt, vs...))
}

// LastPolledAtNotIn applies the NotIn predicate on the "last_polled_at" field.
func LastPolledAtNotIn(vs ...time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldLastPolledAt, vs...))
}

// LastPolledAtGT applies the GT predicate on the "last_polled_at" field.
func LastPolledAtGT(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldLastPolledAt, v))
}

// LastPolledAtGTE applies the GTE predicate on the "last_polled_at" field.
func LastPolledAtGTE(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldLastPolledAt, v))
}

// LastPolledAtLT applies the LT predicate on the "last_polled_at" field.
func LastPolledAtLT(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldLastPolledAt, v))
}

// LastPolledAtLTE applies the LTE predicate on the "last_polled_at" field.
func LastPolledAtLTE(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldLastPolledAt, v))
}

// LastPolledAtIsNil applies the IsNil predicate on the "last_polled_at" field.
func LastPolledAtIsNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIsNull(FieldLastPolledAt))
}

// LastPolledAtNotNil applies the NotNil predicate on the "last_polled_at" field.
func LastPolledAtNotNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotNull(FieldLastPolledAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.FieldNotNull(FieldFinishedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GrokVideoJob) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GrokVideoJob) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GrokVideoJob) predicate.GrokVideoJob {
	return predicate.GrokVideoJob(sql.NotPredicates(p))
}
